<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 ANCOVA with different slopes: interactions | Notes for Ecological Modelling</title>
  <meta name="description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 ANCOVA with different slopes: interactions | Notes for Ecological Modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 ANCOVA with different slopes: interactions | Notes for Ecological Modelling" />
  
  <meta name="twitter:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Tiago A. Marques" />


<meta name="date" content="2024-11-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ANCOVAasLM.html"/>
<link rel="next" href="ContinousInteractions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="mainintro.html"><a href="mainintro.html"><i class="fa fa-check"></i><b>2</b> Preamble</a></li>
<li class="chapter" data-level="3" data-path="aknowledgments.html"><a href="aknowledgments.html"><i class="fa fa-check"></i><b>3</b> Aknowledgments</a></li>
<li class="chapter" data-level="4" data-path="usingRintro.html"><a href="usingRintro.html"><i class="fa fa-check"></i><b>4</b> Using R</a></li>
<li class="chapter" data-level="5" data-path="prelim.html"><a href="prelim.html"><i class="fa fa-check"></i><b>5</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.1" data-path="prelim.html"><a href="prelim.html#lbtb"><i class="fa fa-check"></i><b>5.1</b> Learning by the book</a></li>
<li class="chapter" data-level="5.2" data-path="prelim.html"><a href="prelim.html#ftpt"><i class="fa fa-check"></i><b>5.2</b> Following the paper trail</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="about-regression.html"><a href="about-regression.html"><i class="fa fa-check"></i><b>6</b> About regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="about-regression.html"><a href="about-regression.html#what-is-a-regression"><i class="fa fa-check"></i><b>6.1</b> What is a regression?</a></li>
<li class="chapter" data-level="6.2" data-path="about-regression.html"><a href="about-regression.html#the-general-linear-model"><i class="fa fa-check"></i><b>6.2</b> The general linear model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="handson.html"><a href="handson.html"><i class="fa fa-check"></i><b>7</b> Hands On Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="handson.html"><a href="handson.html#the-assumptions-are-on-the-residuals-not-the-data"><i class="fa fa-check"></i><b>7.1</b> The assumptions are on the residuals, not the data</a></li>
<li class="chapter" data-level="7.2" data-path="handson.html"><a href="handson.html#conditional-versus-marginal-distribution"><i class="fa fa-check"></i><b>7.2</b> Conditional versus marginal distribution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="RIO.html"><a href="RIO.html"><i class="fa fa-check"></i><b>8</b> Regression inside out</a>
<ul>
<li class="chapter" data-level="8.1" data-path="RIO.html"><a href="RIO.html#implementing-a-regression"><i class="fa fa-check"></i><b>8.1</b> Implementing a regression</a></li>
<li class="chapter" data-level="8.2" data-path="RIO.html"><a href="RIO.html#simulating-regression-data"><i class="fa fa-check"></i><b>8.2</b> Simulating regression data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="RIO.html"><a href="RIO.html#what-is-the-effect-of-increasing-the-error-a-simulation-experiment"><i class="fa fa-check"></i><b>8.2.1</b> What is the effect of increasing the error: a simulation experiment</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="RIO.html"><a href="RIO.html#two-tasks-to-further-understand-regression"><i class="fa fa-check"></i><b>8.3</b> Two tasks to further understand regression</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="RIO.html"><a href="RIO.html#task-1"><i class="fa fa-check"></i><b>8.3.1</b> Task 1</a></li>
<li class="chapter" data-level="8.3.2" data-path="RIO.html"><a href="RIO.html#task-2"><i class="fa fa-check"></i><b>8.3.2</b> Task 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html"><i class="fa fa-check"></i><b>9</b> t-tests and ANOVAs are just linear models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#a-one-sample-t-test-is-the-simplest-possible-linear-model"><i class="fa fa-check"></i><b>9.1</b> A one sample t-test is the simplest possible linear model</a></li>
<li class="chapter" data-level="9.2" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#the-t-test"><i class="fa fa-check"></i><b>9.2</b> The t-test</a></li>
<li class="chapter" data-level="9.3" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#anova"><i class="fa fa-check"></i><b>9.3</b> ANOVA</a></li>
<li class="chapter" data-level="9.4" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#a-two-way-anova-and-beyhond-ex-task-do-it-yourself"><i class="fa fa-check"></i><b>9.4</b> A two way ANOVA, and beyhond (ex Task: do it yourself!)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html"><i class="fa fa-check"></i><b>10</b> ANCOVA is (also) just a linear model</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#common-slope-different-intercepts-per-treatment"><i class="fa fa-check"></i><b>10.1</b> Common slope, different intercepts per treatment</a></li>
<li class="chapter" data-level="10.2" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#ANCOVAe"><i class="fa fa-check"></i><b>10.2</b> ANCOVA encore</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#same-story-another-spin"><i class="fa fa-check"></i><b>10.2.1</b> Same story, another spin</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html"><i class="fa fa-check"></i><b>11</b> ANCOVA with different slopes: interactions</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#about-interactions"><i class="fa fa-check"></i><b>11.1</b> About interactions</a></li>
<li class="chapter" data-level="11.2" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#task-1-implementing-the-ancova-with-different-slopes"><i class="fa fa-check"></i><b>11.2</b> Task 1 Implementing the ANCOVA with different slopes</a></li>
<li class="chapter" data-level="11.3" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#task-2-modeling-a-data-set"><i class="fa fa-check"></i><b>11.3</b> Task 2 Modeling a data set</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html"><i class="fa fa-check"></i><b>12</b> Interactions between continous covariates</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#larger-order-interactions"><i class="fa fa-check"></i><b>12.1</b> Larger order interactions</a></li>
<li class="chapter" data-level="12.2" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#conclusion-on-linear-regression"><i class="fa fa-check"></i><b>12.2</b> Conclusion on linear regression</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#conclusion"><i class="fa fa-check"></i><b>12.2.1</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="LMinPractice.html"><a href="LMinPractice.html"><i class="fa fa-check"></i><b>13</b> Real life examples using linear models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="LMinPractice.html"><a href="LMinPractice.html#rikz-data"><i class="fa fa-check"></i><b>13.1</b> RIKZ data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="MLEs.html"><a href="MLEs.html"><i class="fa fa-check"></i><b>14</b> Class 13: 10 11 2020 Maximum likelihood and all that</a>
<ul>
<li class="chapter" data-level="14.1" data-path="MLEs.html"><a href="MLEs.html#maximizing-a-likelihood-algebraically"><i class="fa fa-check"></i><b>14.1</b> Maximizing a likelihood algebraically</a></li>
<li class="chapter" data-level="14.2" data-path="MLEs.html"><a href="MLEs.html#numerically-maximizing-a-likelihood"><i class="fa fa-check"></i><b>14.2</b> Numerically Maximizing a likelihood</a></li>
<li class="chapter" data-level="14.3" data-path="MLEs.html"><a href="MLEs.html#the-case-of-a-gaussian"><i class="fa fa-check"></i><b>14.3</b> The case of a Gaussian</a></li>
<li class="chapter" data-level="14.4" data-path="MLEs.html"><a href="MLEs.html#the-case-of-a-linear-model"><i class="fa fa-check"></i><b>14.4</b> The case of a linear model</a></li>
<li class="chapter" data-level="14.5" data-path="MLEs.html"><a href="MLEs.html#the-really-interesting-case"><i class="fa fa-check"></i><b>14.5</b> The really interesting case</a></li>
<li class="chapter" data-level="14.6" data-path="MLEs.html"><a href="MLEs.html#likelihood-above-and-beyond"><i class="fa fa-check"></i><b>14.6</b> Likelihood, above and beyond</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="GLMs.html"><a href="GLMs.html"><i class="fa fa-check"></i><b>15</b> An introduction to generalized linear models</a>
<ul>
<li class="chapter" data-level="15.1" data-path="GLMs.html"><a href="GLMs.html#what-are-glms"><i class="fa fa-check"></i><b>15.1</b> What are GLMs</a></li>
<li class="chapter" data-level="15.2" data-path="GLMs.html"><a href="GLMs.html#the-link-function"><i class="fa fa-check"></i><b>15.2</b> The link function</a></li>
<li class="chapter" data-level="15.3" data-path="GLMs.html"><a href="GLMs.html#most-useful-glm-families"><i class="fa fa-check"></i><b>15.3</b> Most useful GLM Families</a></li>
<li class="chapter" data-level="15.4" data-path="GLMs.html"><a href="GLMs.html#an-example-analysis"><i class="fa fa-check"></i><b>15.4</b> An example analysis</a></li>
<li class="chapter" data-level="15.5" data-path="GLMs.html"><a href="GLMs.html#an-example-of-a-glm-as-a-detail-within-a-conceptualization-framework"><i class="fa fa-check"></i><b>15.5</b> An example of a GLM as a detail within a conceptualization framework</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="aula15.html"><a href="aula15.html"><i class="fa fa-check"></i><b>16</b> Class 15: 17 11 2020</a></li>
<li class="chapter" data-level="17" data-path="example-1---deviance.html"><a href="example-1---deviance.html"><i class="fa fa-check"></i><b>17</b> Example 1 - deviance</a></li>
<li class="chapter" data-level="18" data-path="example-2---lagartyos-glm.html"><a href="example-2---lagartyos-glm.html"><i class="fa fa-check"></i><b>18</b> Example 2 - lagartyos GLM</a>
<ul>
<li class="chapter" data-level="18.1" data-path="example-2---lagartyos-glm.html"><a href="example-2---lagartyos-glm.html#example-2"><i class="fa fa-check"></i><b>18.1</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="aula16.html"><a href="aula16.html"><i class="fa fa-check"></i><b>19</b> Class 16: 18 11 2020</a>
<ul>
<li class="chapter" data-level="19.1" data-path="aula16.html"><a href="aula16.html#a-logistic-regression-example"><i class="fa fa-check"></i><b>19.1</b> A logistic regression example</a></li>
<li class="chapter" data-level="19.2" data-path="aula16.html"><a href="aula16.html#titanic-example"><i class="fa fa-check"></i><b>19.2</b> Titanic example</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="aula16.html"><a href="aula16.html#análise-exploratoria-de-dados"><i class="fa fa-check"></i><b>19.2.1</b> Análise Exploratoria de Dados</a></li>
<li class="chapter" data-level="19.2.2" data-path="aula16.html"><a href="aula16.html#modelação"><i class="fa fa-check"></i><b>19.2.2</b> Modelação</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="aula16.html"><a href="aula16.html#about-multicollinearity"><i class="fa fa-check"></i><b>19.3</b> About multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="GLMM.html"><a href="GLMM.html"><i class="fa fa-check"></i><b>20</b> Random effects and mixed models</a></li>
<li class="chapter" data-level="21" data-path="aula18.html"><a href="aula18.html"><i class="fa fa-check"></i><b>21</b> Class 18: 25 11 2020</a>
<ul>
<li class="chapter" data-level="21.1" data-path="aula18.html"><a href="aula18.html#presence-of-bats"><i class="fa fa-check"></i><b>21.1</b> Presence of bats</a></li>
<li class="chapter" data-level="21.2" data-path="aula18.html"><a href="aula18.html#sponges"><i class="fa fa-check"></i><b>21.2</b> Sponges</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="aula18.html"><a href="aula18.html#reading-data-in"><i class="fa fa-check"></i><b>21.2.1</b> Reading data in</a></li>
<li class="chapter" data-level="21.2.2" data-path="aula18.html"><a href="aula18.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>21.2.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="21.2.3" data-path="aula18.html"><a href="aula18.html#modelling"><i class="fa fa-check"></i><b>21.2.3</b> Modelling</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="aula18.html"><a href="aula18.html#extra-glm-stuff"><i class="fa fa-check"></i><b>21.3</b> Extra GLM stuff</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>22</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Ecological Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ANCOVAdifslopes" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> ANCOVA with different slopes: interactions<a href="ANCOVAdifslopes.html#ANCOVAdifslopes" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous section we saw an ANCOVA, but we assumed all groups would have the same slope. So the rate of change of the response with the continuous covariate would not depend on the level of the factor covariate. Here we extend that model to consider different slopes per group, and for that we will need interactions.</p>
<div id="about-interactions" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> About interactions<a href="ANCOVAdifslopes.html#about-interactions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Interactions are useful when the influence of a covariate on the response variable depends on the level of a second covariate. As an example, consider two different diets that we are trying to assess the efficacy on terms of weight gain. We record weight gains for both sexes.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="ANCOVAdifslopes.html#cb260-1" tabindex="-1"></a><span class="co">#--------------------------------------------------------</span></span>
<span id="cb260-2"><a href="ANCOVAdifslopes.html#cb260-2" tabindex="-1"></a><span class="co">#Interactions</span></span>
<span id="cb260-3"><a href="ANCOVAdifslopes.html#cb260-3" tabindex="-1"></a><span class="do">#### with factor covariates</span></span>
<span id="cb260-4"><a href="ANCOVAdifslopes.html#cb260-4" tabindex="-1"></a><span class="co">#--------------------------------------------------------</span></span>
<span id="cb260-5"><a href="ANCOVAdifslopes.html#cb260-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb260-6"><a href="ANCOVAdifslopes.html#cb260-6" tabindex="-1"></a>n<span class="ot">=</span><span class="dv">100</span></span>
<span id="cb260-7"><a href="ANCOVAdifslopes.html#cb260-7" tabindex="-1"></a>sexo<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;M&quot;</span>,<span class="st">&quot;F&quot;</span>),<span class="at">each=</span>n)</span>
<span id="cb260-8"><a href="ANCOVAdifslopes.html#cb260-8" tabindex="-1"></a>dieta<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Controlo&quot;</span>,<span class="st">&quot;Nova&quot;</span>),<span class="at">times=</span>n)</span>
<span id="cb260-9"><a href="ANCOVAdifslopes.html#cb260-9" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">10</span><span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">-</span><span class="dv">4</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">2</span><span class="sc">*</span>n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb260-10"><a href="ANCOVAdifslopes.html#cb260-10" tabindex="-1"></a><span class="fu">plot</span>(ys<span class="sc">~</span><span class="fu">as.factor</span>(<span class="fu">paste0</span>(sexo,dieta)))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.1-1.png" width="672" /></p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="ANCOVAdifslopes.html#cb261-1" tabindex="-1"></a>lmSDi<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>sexo<span class="sc">*</span>dieta)</span>
<span id="cb261-2"><a href="ANCOVAdifslopes.html#cb261-2" tabindex="-1"></a><span class="fu">summary</span>(lmSDi)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ sexo * dieta)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7590 -1.2968 -0.1798  1.1942  6.7145 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       9.8022     0.2673  36.675  &lt; 2e-16 ***
## sexoM             3.4188     0.3780   9.045  &lt; 2e-16 ***
## dietaNova         1.9653     0.3780   5.200 5.00e-07 ***
## sexoM:dietaNova  -4.0457     0.5345  -7.569 1.44e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.89 on 196 degrees of freedom
## Multiple R-squared:  0.3015, Adjusted R-squared:  0.2908 
## F-statistic:  28.2 on 3 and 196 DF,  p-value: 3.326e-15</code></pre>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="ANCOVAdifslopes.html#cb263-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.2</span>,<span class="fl">0.2</span>))</span>
<span id="cb263-2"><a href="ANCOVAdifslopes.html#cb263-2" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>sexo, <span class="at">trace.factor=</span>dieta, <span class="at">response=</span>ys)</span>
<span id="cb263-3"><a href="ANCOVAdifslopes.html#cb263-3" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>dieta, <span class="at">trace.factor=</span>sexo, <span class="at">response=</span>ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.1-2.png" width="672" /></p>
<p>We can see what these interaction plots might look like for different realities.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="ANCOVAdifslopes.html#cb264-1" tabindex="-1"></a><span class="co">#interaction plots</span></span>
<span id="cb264-2"><a href="ANCOVAdifslopes.html#cb264-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">121</span>)</span>
<span id="cb264-3"><a href="ANCOVAdifslopes.html#cb264-3" tabindex="-1"></a><span class="co"># different interactions and abcense of interaction</span></span>
<span id="cb264-4"><a href="ANCOVAdifslopes.html#cb264-4" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.2</span>,<span class="fl">0.2</span>))</span>
<span id="cb264-5"><a href="ANCOVAdifslopes.html#cb264-5" tabindex="-1"></a><span class="co">#large negative interaction</span></span>
<span id="cb264-6"><a href="ANCOVAdifslopes.html#cb264-6" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">10</span><span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">-</span><span class="dv">4</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">2</span><span class="sc">*</span>n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb264-7"><a href="ANCOVAdifslopes.html#cb264-7" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>sexo, <span class="at">trace.factor=</span>dieta, <span class="at">response=</span>ys)</span>
<span id="cb264-8"><a href="ANCOVAdifslopes.html#cb264-8" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>dieta, <span class="at">trace.factor=</span>sexo, <span class="at">response=</span>ys)</span>
<span id="cb264-9"><a href="ANCOVAdifslopes.html#cb264-9" tabindex="-1"></a><span class="co">#positive interaction</span></span>
<span id="cb264-10"><a href="ANCOVAdifslopes.html#cb264-10" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">10</span><span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="dv">4</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">2</span><span class="sc">*</span>n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb264-11"><a href="ANCOVAdifslopes.html#cb264-11" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>sexo, <span class="at">trace.factor=</span>dieta, <span class="at">response=</span>ys)</span>
<span id="cb264-12"><a href="ANCOVAdifslopes.html#cb264-12" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>dieta, <span class="at">trace.factor=</span>sexo, <span class="at">response=</span>ys)</span>
<span id="cb264-13"><a href="ANCOVAdifslopes.html#cb264-13" tabindex="-1"></a><span class="co">#no interaction</span></span>
<span id="cb264-14"><a href="ANCOVAdifslopes.html#cb264-14" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">10</span><span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">2</span><span class="sc">*</span>n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb264-15"><a href="ANCOVAdifslopes.html#cb264-15" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>sexo, <span class="at">trace.factor=</span>dieta, <span class="at">response=</span>ys)</span>
<span id="cb264-16"><a href="ANCOVAdifslopes.html#cb264-16" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>dieta, <span class="at">trace.factor=</span>sexo, <span class="at">response=</span>ys)</span>
<span id="cb264-17"><a href="ANCOVAdifslopes.html#cb264-17" tabindex="-1"></a><span class="co">#small negative interaction</span></span>
<span id="cb264-18"><a href="ANCOVAdifslopes.html#cb264-18" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">10</span><span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span>(sexo<span class="sc">==</span><span class="st">&quot;M&quot;</span>)<span class="sc">*</span>(dieta<span class="sc">==</span><span class="st">&quot;Nova&quot;</span>)<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">2</span><span class="sc">*</span>n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb264-19"><a href="ANCOVAdifslopes.html#cb264-19" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>sexo, <span class="at">trace.factor=</span>dieta, <span class="at">response=</span>ys)</span>
<span id="cb264-20"><a href="ANCOVAdifslopes.html#cb264-20" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor=</span>dieta, <span class="at">trace.factor=</span>sexo, <span class="at">response=</span>ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.2-1.png" width="672" /></p>
</div>
<div id="task-1-implementing-the-ancova-with-different-slopes" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Task 1 Implementing the ANCOVA with different slopes<a href="ANCOVAdifslopes.html#task-1-implementing-the-ancova-with-different-slopes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The previous model, explored in Chapter <a href="ANCOVAasLM.html#ANCOVAasLM">10</a>, assumed that the slopes were the same across the different groups. But that might not be the case in many scenarios.</p>
<p>What would change if they were different? We extend the previous case to the scenario where the slope of the relationship is also different per treatment.</p>
<p>We simulate treatments and data, just in the same way as before, but this gives us the option to change things later in this chapter only, and do it separately if we want.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="ANCOVAdifslopes.html#cb265-1" tabindex="-1"></a><span class="co">#----------------------------------------------------------------</span></span>
<span id="cb265-2"><a href="ANCOVAdifslopes.html#cb265-2" tabindex="-1"></a><span class="co">#all slopes different</span></span>
<span id="cb265-3"><a href="ANCOVAdifslopes.html#cb265-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb265-4"><a href="ANCOVAdifslopes.html#cb265-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">200</span></span>
<span id="cb265-5"><a href="ANCOVAdifslopes.html#cb265-5" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb265-6"><a href="ANCOVAdifslopes.html#cb265-6" tabindex="-1"></a>tr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>,<span class="st">&quot;b&quot;</span>,<span class="st">&quot;c&quot;</span>,<span class="st">&quot;d&quot;</span>)</span>
<span id="cb265-7"><a href="ANCOVAdifslopes.html#cb265-7" tabindex="-1"></a>type <span class="ot">&lt;-</span> <span class="fu">rep</span>(tr,<span class="at">each=</span>n<span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb265-8"><a href="ANCOVAdifslopes.html#cb265-8" tabindex="-1"></a>cores <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">each=</span>n<span class="sc">/</span><span class="dv">4</span>)</span></code></pre></div>
<p>Now we simulate the response</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="ANCOVAdifslopes.html#cb266-1" tabindex="-1"></a>ys<span class="ot">=</span><span class="dv">3</span><span class="sc">+</span></span>
<span id="cb266-2"><a href="ANCOVAdifslopes.html#cb266-2" tabindex="-1"></a><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>)))<span class="sc">+</span></span>
<span id="cb266-3"><a href="ANCOVAdifslopes.html#cb266-3" tabindex="-1"></a><span class="dv">4</span><span class="sc">*</span>xs<span class="sc">+</span><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>)))<span class="sc">*</span>xs<span class="sc">+</span></span>
<span id="cb266-4"><a href="ANCOVAdifslopes.html#cb266-4" tabindex="-1"></a><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span></code></pre></div>
<p>If the above code is opaque, we present a different implementation below. Note the code that follows is just the same as the code above, but it might be simpler to understand that the setting implies that we have both different intercepts and slopes per treatment.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="ANCOVAdifslopes.html#cb267-1" tabindex="-1"></a><span class="co">#same as</span></span>
<span id="cb267-2"><a href="ANCOVAdifslopes.html#cb267-2" tabindex="-1"></a>intercept<span class="ot">=</span><span class="dv">3</span><span class="sc">+</span><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>)))</span>
<span id="cb267-3"><a href="ANCOVAdifslopes.html#cb267-3" tabindex="-1"></a>slope<span class="ot">=</span>xs<span class="sc">*</span>(<span class="dv">4</span><span class="sc">+</span><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>))))</span>
<span id="cb267-4"><a href="ANCOVAdifslopes.html#cb267-4" tabindex="-1"></a>ys<span class="ot">=</span>slope<span class="sc">+</span>intercept<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span></code></pre></div>
<p>We can look at the resulting data, as well as the real model that generated the data (as usual, data is the sistematic component induced by the assumed model to which we add some random error)</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="ANCOVAdifslopes.html#cb268-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb268-2"><a href="ANCOVAdifslopes.html#cb268-2" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">col=</span>cores)</span>
<span id="cb268-3"><a href="ANCOVAdifslopes.html#cb268-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb268-4"><a href="ANCOVAdifslopes.html#cb268-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb268-5"><a href="ANCOVAdifslopes.html#cb268-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb268-6"><a href="ANCOVAdifslopes.html#cb268-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.6-1.png" width="672" /></p>
<p>As before, it is actually not that easy to confirm the slopes and intercepts are different, as the intercept is not shown in the above plot. We can zoom out the plot to show us the intercepts (Figure <a href="ANCOVAdifslopes.html#fig:FCR">11.1</a>), which are by definition, where the lines cross the vertical dashed line, i.e., when x=0 in the Cartesian referential.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="ANCOVAdifslopes.html#cb269-1" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">col=</span>cores,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">150</span>))</span>
<span id="cb269-2"><a href="ANCOVAdifslopes.html#cb269-2" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb269-3"><a href="ANCOVAdifslopes.html#cb269-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb269-4"><a href="ANCOVAdifslopes.html#cb269-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb269-5"><a href="ANCOVAdifslopes.html#cb269-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">4</span>)</span>
<span id="cb269-6"><a href="ANCOVAdifslopes.html#cb269-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">5</span>,<span class="dv">3</span><span class="sc">+</span><span class="dv">8</span>,<span class="dv">3</span><span class="sc">+</span><span class="dv">10</span>,<span class="dv">3</span><span class="sc">+</span><span class="dv">12</span>),<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>),<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:FCR"></span>
<img src="ECOMODbook_files/figure-html/FCR-1.png" alt="Zooming out on the data so that the (fifferent) intercepts are visible" width="80%" />
<p class="caption">
Figure 11.1: Zooming out on the data so that the (fifferent) intercepts are visible
</p>
</div>
<p>Now, we implement the ANCOVA linear model, but with an <em>interaction</em> term between the <code>type</code> and <code>xs</code>. An interaction between two variables, say <code>A</code> and <code>B</code>, is defined in R syntax as <code>A*B</code>, and so for the corresponding linear model we specify</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="ANCOVAdifslopes.html#cb270-1" tabindex="-1"></a>lm.ancova2<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs<span class="sc">+</span>type<span class="sc">+</span>xs<span class="sc">*</span>type)</span>
<span id="cb270-2"><a href="ANCOVAdifslopes.html#cb270-2" tabindex="-1"></a>sum.lm.ancova2<span class="ot">=</span><span class="fu">summary</span>(lm.ancova2)</span></code></pre></div>
<p>We can look at the output of the model</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="ANCOVAdifslopes.html#cb271-1" tabindex="-1"></a>sum.lm.ancova2</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs + type + xs * type)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.5511  -2.7070   0.2239   2.2766  11.3763 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.9570     3.1985   2.488 0.013707 *  
## xs            4.2084     0.2143  19.638  &lt; 2e-16 ***
## typeb        10.6830     4.2375   2.521 0.012513 *  
## typec         2.8307     4.3047   0.658 0.511588    
## typed         7.5008     4.4644   1.680 0.094556 .  
## xs:typeb     -0.2342     0.2889  -0.811 0.418617    
## xs:typec      0.9924     0.2836   3.500 0.000579 ***
## xs:typed      1.7875     0.2927   6.106 5.54e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.958 on 192 degrees of freedom
## Multiple R-squared:  0.965,  Adjusted R-squared:  0.9637 
## F-statistic: 755.2 on 7 and 192 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This is an output similar to the corresponding ANOVA table (implemented via <code>aov</code>, the R function that produces ANOVA tables from expressions akin to linear models). The difference is that in such a case the outputs come in terms of the variables, not their levels. This would be</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="ANCOVAdifslopes.html#cb273-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(ys<span class="sc">~</span>xs<span class="sc">+</span>type<span class="sc">+</span>xs<span class="sc">*</span>type))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## xs            1  49119   49119 3134.87  &lt; 2e-16 ***
## type          3  32682   10894  695.28  &lt; 2e-16 ***
## xs:type       3   1034     345   21.99 2.77e-12 ***
## Residuals   192   3008      16                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that the overall F statistic from the regression model has an F-statistic of
755.2, with
7 and
192 degrees of freedom. That corresponds to the composite test with the null hypothesis “are all parameters equal to 0”, which in the ANOVA table, is separated in 3 testes, one for each parameter, with 1, 3 and 3 degrees of freedom each. The residual degrees of freedom are naturally the same in all these tests.</p>
<p>Naturally, we can now evaluate the values of the estimated coefficients, and in particular we can use them to estimate the corresponding regression lines per group. For type <code>a</code> we have this</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="ANCOVAdifslopes.html#cb275-1" tabindex="-1"></a><span class="co">#type a</span></span>
<span id="cb275-2"><a href="ANCOVAdifslopes.html#cb275-2" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>];lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## (Intercept) 
##    7.957025</code></pre>
<pre><code>##       xs 
## 4.208363</code></pre>
<p>in other words, <code>ys</code>=7.9570252+4.2083626 <span class="math inline">\(\times\)</span> <code>xs</code> , for type <code>b</code> we have this</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="ANCOVAdifslopes.html#cb278-1" tabindex="-1"></a><span class="co">#type b</span></span>
<span id="cb278-2"><a href="ANCOVAdifslopes.html#cb278-2" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">3</span>];lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">6</span>]</span></code></pre></div>
<pre><code>## (Intercept) 
##    18.64006</code></pre>
<pre><code>##       xs 
## 3.974212</code></pre>
<p>in other words, <code>ys</code>=18.640062+3.9742116 <span class="math inline">\(\times\)</span> <code>xs</code>, for type <code>c</code> we have this</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="ANCOVAdifslopes.html#cb281-1" tabindex="-1"></a><span class="co">#type c</span></span>
<span id="cb281-2"><a href="ANCOVAdifslopes.html#cb281-2" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">4</span>];lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">7</span>]</span></code></pre></div>
<pre><code>## (Intercept) 
##    10.78774</code></pre>
<pre><code>##       xs 
## 5.200757</code></pre>
<p>in other words, <code>ys</code>=10.7877404+5.2007572 <span class="math inline">\(\times\)</span> <code>xs</code>, and for type <code>d</code> we have this</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="ANCOVAdifslopes.html#cb284-1" tabindex="-1"></a><span class="co">#type d</span></span>
<span id="cb284-2"><a href="ANCOVAdifslopes.html#cb284-2" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">5</span>];lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">8</span>]</span></code></pre></div>
<pre><code>## (Intercept) 
##    15.45779</code></pre>
<pre><code>##       xs 
## 5.995865</code></pre>
<p>in other words, <code>ys</code>=15.4577929+5.995865 <span class="math inline">\(\times\)</span> <code>xs</code>.</p>
<p>we can now add these to the earlier plots, to see how well we have estimated the different lines per treatment</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="ANCOVAdifslopes.html#cb287-1" tabindex="-1"></a><span class="co">#real lines</span></span>
<span id="cb287-2"><a href="ANCOVAdifslopes.html#cb287-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb287-3"><a href="ANCOVAdifslopes.html#cb287-3" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">col=</span>cores)</span>
<span id="cb287-4"><a href="ANCOVAdifslopes.html#cb287-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb287-5"><a href="ANCOVAdifslopes.html#cb287-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb287-6"><a href="ANCOVAdifslopes.html#cb287-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb287-7"><a href="ANCOVAdifslopes.html#cb287-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">4</span>)</span>
<span id="cb287-8"><a href="ANCOVAdifslopes.html#cb287-8" tabindex="-1"></a><span class="co">#estimated lines</span></span>
<span id="cb287-9"><a href="ANCOVAdifslopes.html#cb287-9" tabindex="-1"></a><span class="co">#type a</span></span>
<span id="cb287-10"><a href="ANCOVAdifslopes.html#cb287-10" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb287-11"><a href="ANCOVAdifslopes.html#cb287-11" tabindex="-1"></a><span class="co">#type b</span></span>
<span id="cb287-12"><a href="ANCOVAdifslopes.html#cb287-12" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">3</span>],</span>
<span id="cb287-13"><a href="ANCOVAdifslopes.html#cb287-13" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb287-14"><a href="ANCOVAdifslopes.html#cb287-14" tabindex="-1"></a><span class="co">#type c</span></span>
<span id="cb287-15"><a href="ANCOVAdifslopes.html#cb287-15" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">4</span>],</span>
<span id="cb287-16"><a href="ANCOVAdifslopes.html#cb287-16" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb287-17"><a href="ANCOVAdifslopes.html#cb287-17" tabindex="-1"></a><span class="co">#type b</span></span>
<span id="cb287-18"><a href="ANCOVAdifslopes.html#cb287-18" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">5</span>],</span>
<span id="cb287-19"><a href="ANCOVAdifslopes.html#cb287-19" tabindex="-1"></a>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">4</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb287-20"><a href="ANCOVAdifslopes.html#cb287-20" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">legend =</span> tr,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span>
<span id="cb287-21"><a href="ANCOVAdifslopes.html#cb287-21" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="at">legend =</span><span class="fu">paste</span>(<span class="st">&quot;Estimated&quot;</span>,tr),<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.14-1.png" width="672" /></p>
<p>Remember, if this was a real analysis, you would not know the truth, so at best, you would be able to see the predicted lines, but not the real lines, just as in the plot below</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="ANCOVAdifslopes.html#cb288-1" tabindex="-1"></a><span class="co"># In real life, we only see this</span></span>
<span id="cb288-2"><a href="ANCOVAdifslopes.html#cb288-2" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">col=</span>cores)</span>
<span id="cb288-3"><a href="ANCOVAdifslopes.html#cb288-3" tabindex="-1"></a><span class="co">#plot the lines</span></span>
<span id="cb288-4"><a href="ANCOVAdifslopes.html#cb288-4" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">lwd=</span><span class="dv">1</span>,<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb288-5"><a href="ANCOVAdifslopes.html#cb288-5" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">3</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">lwd=</span><span class="dv">1</span>,<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb288-6"><a href="ANCOVAdifslopes.html#cb288-6" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">4</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">lwd=</span><span class="dv">1</span>,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb288-7"><a href="ANCOVAdifslopes.html#cb288-7" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">5</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">lwd=</span><span class="dv">1</span>,<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb288-8"><a href="ANCOVAdifslopes.html#cb288-8" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="at">legend =</span><span class="fu">paste</span>(<span class="st">&quot;Estimated&quot;</span>,tr),<span class="at">lwd=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.15-1.png" width="672" /></p>
<p>In the previous image the estimated lines were very consistent with the known truth. This would be different if we had less information, i.e., less data. The following image represents the same scenario, but where instead of 200 observations in total, we only had</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="ANCOVAdifslopes.html#cb289-1" tabindex="-1"></a><span class="co">#all slopes different</span></span>
<span id="cb289-2"><a href="ANCOVAdifslopes.html#cb289-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb289-3"><a href="ANCOVAdifslopes.html#cb289-3" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">20</span></span>
<span id="cb289-4"><a href="ANCOVAdifslopes.html#cb289-4" tabindex="-1"></a>xs3 <span class="ot">&lt;-</span> <span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb289-5"><a href="ANCOVAdifslopes.html#cb289-5" tabindex="-1"></a>tr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>,<span class="st">&quot;b&quot;</span>,<span class="st">&quot;c&quot;</span>,<span class="st">&quot;d&quot;</span>)</span>
<span id="cb289-6"><a href="ANCOVAdifslopes.html#cb289-6" tabindex="-1"></a>type3 <span class="ot">&lt;-</span> <span class="fu">rep</span>(tr,<span class="at">each=</span>n<span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb289-7"><a href="ANCOVAdifslopes.html#cb289-7" tabindex="-1"></a>cores3 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">each=</span>n<span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb289-8"><a href="ANCOVAdifslopes.html#cb289-8" tabindex="-1"></a>ys3<span class="ot">=</span><span class="dv">3</span><span class="sc">+</span></span>
<span id="cb289-9"><a href="ANCOVAdifslopes.html#cb289-9" tabindex="-1"></a><span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>)))<span class="sc">+</span></span>
<span id="cb289-10"><a href="ANCOVAdifslopes.html#cb289-10" tabindex="-1"></a><span class="dv">4</span><span class="sc">*</span>xs3<span class="sc">+</span><span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="fu">ifelse</span>(type3<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>)))<span class="sc">*</span>xs3<span class="sc">+</span></span>
<span id="cb289-11"><a href="ANCOVAdifslopes.html#cb289-11" tabindex="-1"></a><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb289-12"><a href="ANCOVAdifslopes.html#cb289-12" tabindex="-1"></a>lm.ancova3<span class="ot">=</span><span class="fu">lm</span>(ys3<span class="sc">~</span>xs3<span class="sc">+</span>type3<span class="sc">+</span>xs3<span class="sc">*</span>type3)</span>
<span id="cb289-13"><a href="ANCOVAdifslopes.html#cb289-13" tabindex="-1"></a><span class="co">#real lines</span></span>
<span id="cb289-14"><a href="ANCOVAdifslopes.html#cb289-14" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb289-15"><a href="ANCOVAdifslopes.html#cb289-15" tabindex="-1"></a><span class="fu">plot</span>(xs3,ys3,<span class="at">col=</span>cores3)</span>
<span id="cb289-16"><a href="ANCOVAdifslopes.html#cb289-16" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb289-17"><a href="ANCOVAdifslopes.html#cb289-17" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb289-18"><a href="ANCOVAdifslopes.html#cb289-18" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb289-19"><a href="ANCOVAdifslopes.html#cb289-19" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="sc">+</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">4</span>)</span>
<span id="cb289-20"><a href="ANCOVAdifslopes.html#cb289-20" tabindex="-1"></a><span class="co">#estimated lines</span></span>
<span id="cb289-21"><a href="ANCOVAdifslopes.html#cb289-21" tabindex="-1"></a><span class="co">#type a</span></span>
<span id="cb289-22"><a href="ANCOVAdifslopes.html#cb289-22" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">1</span>],lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb289-23"><a href="ANCOVAdifslopes.html#cb289-23" tabindex="-1"></a><span class="co">#type b</span></span>
<span id="cb289-24"><a href="ANCOVAdifslopes.html#cb289-24" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">3</span>],</span>
<span id="cb289-25"><a href="ANCOVAdifslopes.html#cb289-25" tabindex="-1"></a>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb289-26"><a href="ANCOVAdifslopes.html#cb289-26" tabindex="-1"></a><span class="co">#type c</span></span>
<span id="cb289-27"><a href="ANCOVAdifslopes.html#cb289-27" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">4</span>],</span>
<span id="cb289-28"><a href="ANCOVAdifslopes.html#cb289-28" tabindex="-1"></a>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb289-29"><a href="ANCOVAdifslopes.html#cb289-29" tabindex="-1"></a><span class="co">#type b</span></span>
<span id="cb289-30"><a href="ANCOVAdifslopes.html#cb289-30" tabindex="-1"></a><span class="fu">abline</span>(lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">5</span>],</span>
<span id="cb289-31"><a href="ANCOVAdifslopes.html#cb289-31" tabindex="-1"></a>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova3<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">4</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb289-32"><a href="ANCOVAdifslopes.html#cb289-32" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">legend =</span> tr,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span>
<span id="cb289-33"><a href="ANCOVAdifslopes.html#cb289-33" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="at">legend =</span><span class="fu">paste</span>(<span class="st">&quot;Estimated&quot;</span>,tr),<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>As expected, in this plot the different estimated lines are considerably further away from the real lines. It is nonetheless quite remarkable how with only 5 points per group, we still obtain estimates not that far from the truth. However, if one looks at the summary of the model</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="ANCOVAdifslopes.html#cb290-1" tabindex="-1"></a><span class="fu">summary</span>(lm.ancova3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys3 ~ xs3 + type3 + xs3 * type3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5796 -2.3670 -0.1640  0.9371  9.1474 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -1.6002    11.1033  -0.144    0.888    
## xs3           4.7503     0.7005   6.781 1.96e-05 ***
## type3b        5.9856    14.7514   0.406    0.692    
## type3c        3.6526    15.6372   0.234    0.819    
## type3d       23.9730    14.8631   1.613    0.133    
## xs3:type3b    0.2205     0.9740   0.226    0.825    
## xs3:type3c    0.9038     0.9924   0.911    0.380    
## xs3:type3d    0.5410     1.0006   0.541    0.599    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.836 on 12 degrees of freedom
## Multiple R-squared:  0.9657, Adjusted R-squared:  0.9457 
## F-statistic: 48.26 on 7 and 12 DF,  p-value: 7.539e-08</code></pre>
<p>none of the interaction terms would be considered relevant at the usual significance levels. In other words, with such few data we would not be able to distinguish that the slope was different in the different groups, and a common slope model would be preferred.</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="ANCOVAdifslopes.html#cb292-1" tabindex="-1"></a>lm.ancova3b<span class="ot">=</span><span class="fu">lm</span>(ys3<span class="sc">~</span>xs3<span class="sc">+</span>type3)</span>
<span id="cb292-2"><a href="ANCOVAdifslopes.html#cb292-2" tabindex="-1"></a><span class="fu">AIC</span>(lm.ancova3,lm.ancova3b)</span></code></pre></div>
<pre><code>##             df      AIC
## lm.ancova3   9 118.3212
## lm.ancova3b  6 113.8420</code></pre>
<p>It is interesting to note that the slopes were in general closer to the true values than the intercepts.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="ANCOVAdifslopes.html#cb294-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb294-2"><a href="ANCOVAdifslopes.html#cb294-2" tabindex="-1"></a><span class="co">#true intercepts</span></span>
<span id="cb294-3"><a href="ANCOVAdifslopes.html#cb294-3" tabindex="-1"></a>TI<span class="ot">&lt;-</span><span class="fu">unique</span>(<span class="dv">3</span><span class="sc">+</span><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>))))</span>
<span id="cb294-4"><a href="ANCOVAdifslopes.html#cb294-4" tabindex="-1"></a><span class="co">#true slopes</span></span>
<span id="cb294-5"><a href="ANCOVAdifslopes.html#cb294-5" tabindex="-1"></a>TS<span class="ot">&lt;-</span><span class="fu">unique</span>(<span class="dv">4</span><span class="sc">+</span><span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="fu">ifelse</span>(type<span class="sc">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>))))</span>
<span id="cb294-6"><a href="ANCOVAdifslopes.html#cb294-6" tabindex="-1"></a><span class="co">#estimated intercepts</span></span>
<span id="cb294-7"><a href="ANCOVAdifslopes.html#cb294-7" tabindex="-1"></a>EI<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">c</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">3</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">4</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">5</span>]),<span class="dv">2</span>)</span>
<span id="cb294-8"><a href="ANCOVAdifslopes.html#cb294-8" tabindex="-1"></a><span class="co">#estimated slopes</span></span>
<span id="cb294-9"><a href="ANCOVAdifslopes.html#cb294-9" tabindex="-1"></a>ES<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">c</span>(lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">6</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">7</span>],lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lm.ancova2<span class="sc">$</span>coefficients[<span class="dv">8</span>]),<span class="dv">2</span>)</span>
<span id="cb294-10"><a href="ANCOVAdifslopes.html#cb294-10" tabindex="-1"></a><span class="co">#pooled table</span></span>
<span id="cb294-11"><a href="ANCOVAdifslopes.html#cb294-11" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">cbind</span>(<span class="fu">c</span>(<span class="st">&quot;Type&quot;</span>,<span class="st">&quot;Intercept (true)&quot;</span>,<span class="st">&quot;Intercept (estimated)&quot;</span>,<span class="st">&quot;Slope (true)&quot;</span>,<span class="st">&quot;Slope (estimated)&quot;</span>),<span class="fu">rbind</span>(<span class="fu">unique</span>(type),TI,EI,TS,ES)))</span></code></pre></div>
<table>
<colgroup>
<col width="4%" />
<col width="30%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left"></th>
<th align="left">(Intercept)</th>
<th align="left">(Intercept)</th>
<th align="left">(Intercept)</th>
<th align="left">(Intercept)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Type</td>
<td align="left">a</td>
<td align="left">b</td>
<td align="left">c</td>
<td align="left">d</td>
</tr>
<tr class="even">
<td align="left">TI</td>
<td align="left">Intercept (true)</td>
<td align="left">8</td>
<td align="left">11</td>
<td align="left">13</td>
<td align="left">15</td>
</tr>
<tr class="odd">
<td align="left">EI</td>
<td align="left">Intercept (estimated)</td>
<td align="left">7.96</td>
<td align="left">18.64</td>
<td align="left">10.79</td>
<td align="left">15.46</td>
</tr>
<tr class="even">
<td align="left">TS</td>
<td align="left">Slope (true)</td>
<td align="left">4.2</td>
<td align="left">4.5</td>
<td align="left">5</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">ES</td>
<td align="left">Slope (estimated)</td>
<td align="left">4.21</td>
<td align="left">3.97</td>
<td align="left">5.2</td>
<td align="left">6</td>
</tr>
</tbody>
</table>
<p>Can you think about an intuitive reason for that being the case? The answer lies in figure <a href="ANCOVAdifslopes.html#fig:FCR">11.1</a>. There is no data near the intercept, so there is actually more information about the slope than about the intercept. Things could have been different if the data for the continous response was also available around the value 0.</p>
</div>
<div id="task-2-modeling-a-data-set" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">11.3</span> Task 2 Modeling a data set<a href="ANCOVAdifslopes.html#task-2-modeling-a-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In a given dataset we might want to explain a continuous variable as a function of a couple of explanatory variables, specifically a continuous variable and a factor. As we have seen before, this could be attempted via an ANCOVA, with or without an interaction term.Therefore, a relevant question might be to know if the interaction is needed or not, or in other words, if the different lines expressing the relationship between the continuous covariate and the response might be have different slopes per level of the factor covariate, or if on the other hand, a common slope might be possible, with different per level of the factor covariate. A third even simpler model is the one where the factor covariate is not relevant at all, or, in other words, single line would be the most parsimonious way to model the data.</p>
<p>We illustrate that with the data set <code>data4lines.csv</code> that we considered before in chapter <a href="#aula7"><strong>??</strong></a>, which was created using the website <a href="https://drawdata.xyz/" class="uri">https://drawdata.xyz/</a>.</p>
<p>To make our story a bit more intersting we again come up with a narrative. A biologist is interested in estimating what might have been the weight of a fish for which he found an operculum in the in the stomach of a dead otter (<em>Lutra lutra</em>). The operculum was 300 mm in diameter. He knows the fish was a barbel (genera: <em>Barbus</em>). We will call this biologist Carlos. His wife is called Conceição, and Conceição enjoys thinking about hard questions. She thinks <em>stongly</em> about all the hard questions, and when she does her eyebrows raise in a way that Carlos fears. Carlos found the dead otter in the margins of the Guadiana river in Portugal. It seems hard to believe that the otter might have eaten such a large fish. It might have been the largest fish ever eaten by a <em>Lutra lutra</em>, which the biologist would love to report in the next Ichtiology congress. To answer his question he visited the museum and he was able to find a sample of fish from the genus <em>Barbus</em>. Therefore he labouriosly weighed fish and measured opeculuns… The resulting data are our data!</p>
<p>Carlos reads the data in</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="ANCOVAdifslopes.html#cb295-1" tabindex="-1"></a>folder<span class="ot">&lt;-</span><span class="st">&quot;extfiles/&quot;</span></span>
<span id="cb295-2"><a href="ANCOVAdifslopes.html#cb295-2" tabindex="-1"></a><span class="co">#folder&lt;-&quot;../Aula7 14 10 2020/&quot;</span></span>
<span id="cb295-3"><a href="ANCOVAdifslopes.html#cb295-3" tabindex="-1"></a>d4l <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file=</span><span class="fu">paste0</span>(folder,<span class="st">&quot;data4lines.csv&quot;</span>))</span>
<span id="cb295-4"><a href="ANCOVAdifslopes.html#cb295-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d4l)</span></code></pre></div>
<p>He plots the data ad he sees a pattern that seems to be somewaht linear. He knows about linear regression and he fits a line to the data, and then shows the resulting plot with data, model and predictions to Conceição.</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="ANCOVAdifslopes.html#cb296-1" tabindex="-1"></a>lm0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l)</span></code></pre></div>
<p>Carlos is winning, claiming that unfortunately, he suspects that the fish was not the largest ever reported. A Spanish ictiologist reported an otter having eaten a fish with 220 grams. And with his model, he predicts the opperculum belonged to a fish with a weight of about 213.7 gr (<a href="ANCOVAdifslopes.html#fig:wod">11.2</a>).</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="ANCOVAdifslopes.html#cb297-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb297-2"><a href="ANCOVAdifslopes.html#cb297-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">xlab=</span> <span class="st">&quot;Operculum diameters (mm)&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Fish length (gr)&quot;</span>,<span class="at">data=</span>d4l)</span>
<span id="cb297-3"><a href="ANCOVAdifslopes.html#cb297-3" tabindex="-1"></a><span class="fu">abline</span>(lm0,<span class="at">lty=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb297-4"><a href="ANCOVAdifslopes.html#cb297-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span>sizeo,<span class="at">h=</span>lm0<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lm0<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">*</span>sizeo,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:wod"></span>
<img src="ECOMODbook_files/figure-html/wod-1.png" alt="Pooled model of fish weight as a function of operculum diameter. Dashed lines represent predictions for a fish with a 300 mm operculum." width="80%" />
<p class="caption">
Figure 11.2: Pooled model of fish weight as a function of operculum diameter. Dashed lines represent predictions for a fish with a 300 mm operculum.
</p>
</div>
<p>Conceição looks at the plots, wonders once again why she married Carlos, and asks: “What was the actual species of the operculum in your dead otter? And by the way, please, for the last time, can you put the dead otter in the garbage? It is the second time that I confuse it with a rabbit in the freezer…! One day you might have a bad surprise for dinner!”. Carlos thinks about this as says, it was <em>Barbus sclateri</em>. And Maria says: “Well, is the relationship between operculum diameter and fish length the same for all the species?”. Carlos - perhaps not the sharpest tool in the box as we by now have come to realize - nonetheless manages to realize what Conceição is asking about. He knows the animals in the museum were identified to the species level, and he redoes the plot coloring the points by species.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="ANCOVAdifslopes.html#cb298-1" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>d4l,<span class="at">pch=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.20-1.png" width="672" /></p>
<p>And the question that now arises in Carlos mind is, what might the best model to represent this data set, where he has measurements of two numeric variables, <code>weight~diameter</code> across 4 groups of observations, defined by <code>species</code>.</p>
<p>Carlos decides he can fit a linear model with both <code>x</code> and <code>z</code> as independent variables, without an interaction. Note this is the conventional ANCOVA model, just as we did before.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="ANCOVAdifslopes.html#cb299-1" tabindex="-1"></a><span class="co">#fit model per group</span></span>
<span id="cb299-2"><a href="ANCOVAdifslopes.html#cb299-2" tabindex="-1"></a>lmANC<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>z,<span class="at">data=</span>d4l)</span>
<span id="cb299-3"><a href="ANCOVAdifslopes.html#cb299-3" tabindex="-1"></a><span class="fu">summary</span>(lmANC)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z, data = d4l)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -90.01 -35.01   2.54  35.51 108.10 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  45.51813   13.83069   3.291  0.00128 ** 
## x             0.39657    0.02516  15.763  &lt; 2e-16 ***
## zb           54.92376   12.11597   4.533 1.28e-05 ***
## zc          128.20339   11.72572  10.934  &lt; 2e-16 ***
## zd           22.82412   10.26509   2.223  0.02787 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 42.5 on 133 degrees of freedom
## Multiple R-squared:  0.7332, Adjusted R-squared:  0.7252 
## F-statistic: 91.38 on 4 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Maria reminds him again that life is more complicated than what he’d like to imagine: “Why don’t you try a model with an interaction term between opperculum diameter and species?”. And so he does.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="ANCOVAdifslopes.html#cb301-1" tabindex="-1"></a><span class="co">#fit model per group, with interaction</span></span>
<span id="cb301-2"><a href="ANCOVAdifslopes.html#cb301-2" tabindex="-1"></a>lmlinesI<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>z<span class="sc">+</span>x<span class="sc">:</span>z,<span class="at">data=</span>d4l)</span>
<span id="cb301-3"><a href="ANCOVAdifslopes.html#cb301-3" tabindex="-1"></a><span class="fu">summary</span>(lmlinesI)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z + x:z, data = d4l)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -77.569 -15.787   2.848  17.776  60.875 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -84.72064   19.98946  -4.238 4.24e-05 ***
## x             0.69346    0.04380  15.831  &lt; 2e-16 ***
## zb          109.96907   25.87243   4.250 4.04e-05 ***
## zc          187.01780   24.87546   7.518 8.03e-12 ***
## zd          223.27435   21.82006  10.233  &lt; 2e-16 ***
## x:zb         -0.08161    0.06222  -1.312    0.192    
## x:zc         -0.08902    0.05954  -1.495    0.137    
## x:zd         -0.49630    0.04926 -10.075  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 28.09 on 130 degrees of freedom
## Multiple R-squared:  0.8861, Adjusted R-squared:   0.88 
## F-statistic: 144.5 on 7 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>It seems like, based on AIC, the model with the interaction is the most parsimonious (remember: most parcimonious model is the one with lowest AIC)!</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="ANCOVAdifslopes.html#cb303-1" tabindex="-1"></a><span class="fu">AIC</span>(lm0,lmANC,lmlinesI)</span></code></pre></div>
<pre><code>##          df      AIC
## lm0       3 1533.741
## lmANC     6 1433.414
## lmlinesI  9 1321.927</code></pre>
<p>Which if you ignore the story for a moment, makes total sence, since that indeed we had one line for one of the groups (<code>z</code>) that had a different slope! And that is the significant interaction term above, indicating it is different from the slope of group <code>a</code>.</p>
<p>Now lets go back to the data. Remember a plot we had on this dataset before?We noted the plot was messy, including the pooled regression (the thick black line), the regressions fitted to independent data sets, one for each species (museums before!) (the solid lines), and the regressions resulting from the model with species as a factor covariate (dotted-dashed lines).</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="ANCOVAdifslopes.html#cb305-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb305-2"><a href="ANCOVAdifslopes.html#cb305-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>d4l,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb305-3"><a href="ANCOVAdifslopes.html#cb305-3" tabindex="-1"></a><span class="co">#completely independet regression lines</span></span>
<span id="cb305-4"><a href="ANCOVAdifslopes.html#cb305-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;a&quot;</span>,]),<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb305-5"><a href="ANCOVAdifslopes.html#cb305-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;b&quot;</span>,]),<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb305-6"><a href="ANCOVAdifslopes.html#cb305-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;c&quot;</span>,]),<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb305-7"><a href="ANCOVAdifslopes.html#cb305-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;d&quot;</span>,]),<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb305-8"><a href="ANCOVAdifslopes.html#cb305-8" tabindex="-1"></a><span class="co">#fit model to pooled data</span></span>
<span id="cb305-9"><a href="ANCOVAdifslopes.html#cb305-9" tabindex="-1"></a>lmlinesG<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l)</span>
<span id="cb305-10"><a href="ANCOVAdifslopes.html#cb305-10" tabindex="-1"></a><span class="co">#these are the wrong lines... why?</span></span>
<span id="cb305-11"><a href="ANCOVAdifslopes.html#cb305-11" tabindex="-1"></a><span class="fu">abline</span>(lmlinesG,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb305-12"><a href="ANCOVAdifslopes.html#cb305-12" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb305-13"><a href="ANCOVAdifslopes.html#cb305-13" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb305-14"><a href="ANCOVAdifslopes.html#cb305-14" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb305-15"><a href="ANCOVAdifslopes.html#cb305-15" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.24-1.png" width="672" /></p>
<p>Now we can remove the independent lines (to clean it up a bit!) and just leave the no interaction model estimated values, then add the estimated lines from the interaction model below. Remember, AIC says its the ones from the interactioon model that are the best representation of the data.</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="ANCOVAdifslopes.html#cb306-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb306-2"><a href="ANCOVAdifslopes.html#cb306-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>d4l,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb306-3"><a href="ANCOVAdifslopes.html#cb306-3" tabindex="-1"></a><span class="co"># #completely independent regression lines</span></span>
<span id="cb306-4"><a href="ANCOVAdifslopes.html#cb306-4" tabindex="-1"></a><span class="co"># abline(lm(y~x,data=d4l[d4l$z==&quot;a&quot;,]),col=1,lty=4)</span></span>
<span id="cb306-5"><a href="ANCOVAdifslopes.html#cb306-5" tabindex="-1"></a><span class="co"># abline(lm(y~x,data=d4l[d4l$z==&quot;b&quot;,]),col=2,lty=4)</span></span>
<span id="cb306-6"><a href="ANCOVAdifslopes.html#cb306-6" tabindex="-1"></a><span class="co"># abline(lm(y~x,data=d4l[d4l$z==&quot;c&quot;,]),col=3,lty=4)</span></span>
<span id="cb306-7"><a href="ANCOVAdifslopes.html#cb306-7" tabindex="-1"></a><span class="co"># abline(lm(y~x,data=d4l[d4l$z==&quot;d&quot;,]),col=4,lty=4)</span></span>
<span id="cb306-8"><a href="ANCOVAdifslopes.html#cb306-8" tabindex="-1"></a><span class="co"># no interaction lines</span></span>
<span id="cb306-9"><a href="ANCOVAdifslopes.html#cb306-9" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb306-10"><a href="ANCOVAdifslopes.html#cb306-10" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb306-11"><a href="ANCOVAdifslopes.html#cb306-11" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb306-12"><a href="ANCOVAdifslopes.html#cb306-12" tabindex="-1"></a><span class="fu">abline</span>(lmANC<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmANC<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmANC<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">4</span>)</span>
<span id="cb306-13"><a href="ANCOVAdifslopes.html#cb306-13" tabindex="-1"></a><span class="co"># model with interaction lines</span></span>
<span id="cb306-14"><a href="ANCOVAdifslopes.html#cb306-14" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb306-15"><a href="ANCOVAdifslopes.html#cb306-15" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb306-16"><a href="ANCOVAdifslopes.html#cb306-16" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb306-17"><a href="ANCOVAdifslopes.html#cb306-17" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">5</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.25-1.png" width="672" /></p>
<p>Likewise, we could compare the lines from independent lines to those of the interaction model.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="ANCOVAdifslopes.html#cb307-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb307-2"><a href="ANCOVAdifslopes.html#cb307-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>d4l,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb307-3"><a href="ANCOVAdifslopes.html#cb307-3" tabindex="-1"></a><span class="co">#completely independent regression lines</span></span>
<span id="cb307-4"><a href="ANCOVAdifslopes.html#cb307-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;a&quot;</span>,]),<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb307-5"><a href="ANCOVAdifslopes.html#cb307-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;b&quot;</span>,]),<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb307-6"><a href="ANCOVAdifslopes.html#cb307-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;c&quot;</span>,]),<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb307-7"><a href="ANCOVAdifslopes.html#cb307-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>d4l[d4l<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;d&quot;</span>,]),<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb307-8"><a href="ANCOVAdifslopes.html#cb307-8" tabindex="-1"></a><span class="co"># model with interaction lines</span></span>
<span id="cb307-9"><a href="ANCOVAdifslopes.html#cb307-9" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb307-10"><a href="ANCOVAdifslopes.html#cb307-10" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb307-11"><a href="ANCOVAdifslopes.html#cb307-11" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb307-12"><a href="ANCOVAdifslopes.html#cb307-12" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">5</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.26-1.png" width="672" /></p>
<p>It is interesting to see that they are not very different, which is perhaps surprising but… actually… not surprising. Both use exaclty 8 parameters to describe the data… it’s the same thing!!! Linear models are cool :)</p>
<p>OK, I have completely forgoten about Carlos and Conceição… or maybe it’s too late and I am just sleepy. But if the right model for <em>Barbus sclatery</em>, which happens to correspond to the “green” species, is the one based on the interaction term, then… the fish weight might be 283.6, as shown below.</p>
<p>Carlos might have something to present at the congress after all! He goes to sleep, happy. As he is starting to dream with his “best talk” award he still manages to hear Conceição saying something in the distance like “… have you… considered… variability … prediction… maybe not realy larger than 220 gr…”. The last thought that goes through his mind before the dream turns into a nightmare where he is on that congress naked is… “Why did I married that woman”?</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="ANCOVAdifslopes.html#cb308-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb308-2"><a href="ANCOVAdifslopes.html#cb308-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>d4l,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb308-3"><a href="ANCOVAdifslopes.html#cb308-3" tabindex="-1"></a><span class="co">#completely independent regression lines</span></span>
<span id="cb308-4"><a href="ANCOVAdifslopes.html#cb308-4" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb308-5"><a href="ANCOVAdifslopes.html#cb308-5" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">6</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb308-6"><a href="ANCOVAdifslopes.html#cb308-6" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">7</span>],<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb308-7"><a href="ANCOVAdifslopes.html#cb308-7" tabindex="-1"></a><span class="fu">abline</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">8</span>],<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb308-8"><a href="ANCOVAdifslopes.html#cb308-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">300</span>,<span class="at">h=</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">4</span>]<span class="sc">+</span>(lmlinesI<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>lmlinesI<span class="sc">$</span>coefficients[<span class="dv">7</span>])<span class="sc">*</span>sizeo,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a11.27-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ANCOVAasLM.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ContinousInteractions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ECOMODbook.pdf", "ECOMODbook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
