<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Class 11: 03 10 2020 ANCOVA with different slopes: interactions | Notes for Ecological Modelling</title>
  <meta name="description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Class 11: 03 10 2020 ANCOVA with different slopes: interactions | Notes for Ecological Modelling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Class 11: 03 10 2020 ANCOVA with different slopes: interactions | Notes for Ecological Modelling" />
  
  <meta name="twitter:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Tiago A. Marques, Susana França, Ana Sofia Reboleira" />


<meta name="date" content="2020-10-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="aula10.html"/>
<link rel="next" href="final-words.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#what-is-a-regression"><i class="fa fa-check"></i><b>2.1</b> What is a regression?</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#the-general-linear-model"><i class="fa fa-check"></i><b>2.2</b> The general linear model</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#bookdown-template-leftovers"><i class="fa fa-check"></i><b>2.3</b> Bookdown template leftovers</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="aula6.html"><a href="aula6.html"><i class="fa fa-check"></i><b>3</b> Class 6 13 10 2020</a><ul>
<li class="chapter" data-level="3.1" data-path="aula6.html"><a href="aula6.html#implementing-a-regression"><i class="fa fa-check"></i><b>3.1</b> Implementing a regression</a></li>
<li class="chapter" data-level="3.2" data-path="aula6.html"><a href="aula6.html#simulating-regression-data"><i class="fa fa-check"></i><b>3.2</b> Simulating regression data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="aula6.html"><a href="aula6.html#what-is-the-effect-of-increasing-the-error-a-simulation-experiment"><i class="fa fa-check"></i><b>3.2.1</b> What is the effect of increasing the error: a simulation experiment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="aula7.html"><a href="aula7.html"><i class="fa fa-check"></i><b>4</b> Class 7 14 10 2020</a><ul>
<li class="chapter" data-level="4.1" data-path="aula7.html"><a href="aula7.html#task-1"><i class="fa fa-check"></i><b>4.1</b> Task 1</a></li>
<li class="chapter" data-level="4.2" data-path="aula7.html"><a href="aula7.html#task-2"><i class="fa fa-check"></i><b>4.2</b> Task 2</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="aula8.html"><a href="aula8.html"><i class="fa fa-check"></i><b>5</b> Class 8 20 10 2020 - t-test and ANOVA are just linear models</a><ul>
<li class="chapter" data-level="5.1" data-path="aula8.html"><a href="aula8.html#the-t-test"><i class="fa fa-check"></i><b>5.1</b> The t-test</a></li>
<li class="chapter" data-level="5.2" data-path="aula8.html"><a href="aula8.html#anova"><i class="fa fa-check"></i><b>5.2</b> ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="aula9.html"><a href="aula9.html"><i class="fa fa-check"></i><b>6</b> Class 9: 21 10 2020 - ANCOVA is (also) just a linear model</a><ul>
<li class="chapter" data-level="6.1" data-path="aula9.html"><a href="aula9.html#common-slope-different-intercepts-per-treatment"><i class="fa fa-check"></i><b>6.1</b> Common slope, different intercepts per treatment</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="aula10.html"><a href="aula10.html"><i class="fa fa-check"></i><b>7</b> Class 10: 27 10 2020</a><ul>
<li class="chapter" data-level="7.1" data-path="aula10.html"><a href="aula10.html#same-story-another-spin"><i class="fa fa-check"></i><b>7.1</b> Same story, another spin</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="aula11.html"><a href="aula11.html"><i class="fa fa-check"></i><b>8</b> Class 11: 03 10 2020 ANCOVA with different slopes: interactions</a><ul>
<li class="chapter" data-level="8.1" data-path="aula11.html"><a href="aula11.html#modeling-a-data-set"><i class="fa fa-check"></i><b>8.1</b> Modeling a data set</a></li>
<li class="chapter" data-level="8.2" data-path="aula11.html"><a href="aula11.html#conclusion"><i class="fa fa-check"></i><b>8.2</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>9</b> Final Words</a></li>
<li class="chapter" data-level="10" data-path="agradecimentos.html"><a href="agradecimentos.html"><i class="fa fa-check"></i><b>10</b> Agradecimentos</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Ecological Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="aula11" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Class 11: 03 10 2020 ANCOVA with different slopes: interactions</h1>
<p>The previous model assumed that the slopes were the same across the different groups. What woud change if they were different? We extend the previous case to where the slope of the relationship is also different per treatment.</p>
<p>Simulate treatments, same as before, but this gives us the option to change later separately if we want.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1"><span class="co">#----------------------------------------------------------------</span></a>
<a class="sourceLine" id="cb212-2" title="2"><span class="co">#all slopes different</span></a>
<a class="sourceLine" id="cb212-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb212-4" title="4">xs &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">200</span>,<span class="dv">10</span>,<span class="dv">20</span>)</a>
<a class="sourceLine" id="cb212-5" title="5">tr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;a&quot;</span>,<span class="st">&quot;b&quot;</span>,<span class="st">&quot;c&quot;</span>,<span class="st">&quot;d&quot;</span>)</a>
<a class="sourceLine" id="cb212-6" title="6">type &lt;-<span class="st"> </span><span class="kw">rep</span>(tr,<span class="dt">each=</span><span class="dv">50</span>)</a>
<a class="sourceLine" id="cb212-7" title="7">cores &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dt">each=</span><span class="dv">50</span>)</a></code></pre></div>
<p>Now we simulate the response</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1">ys=<span class="dv">3</span><span class="op">+</span></a>
<a class="sourceLine" id="cb213-2" title="2"><span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>)))<span class="op">+</span></a>
<a class="sourceLine" id="cb213-3" title="3"><span class="dv">4</span><span class="op">*</span>xs<span class="op">+</span><span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>)))<span class="op">*</span>xs<span class="op">+</span></a>
<a class="sourceLine" id="cb213-4" title="4"><span class="kw">rnorm</span>(<span class="dv">200</span>,<span class="dv">0</span>,<span class="dv">4</span>)</a></code></pre></div>
<p>note this is the same as what we have below, but below it might be simpler to understand that these do correspond to different intercepts and slopes per treatment</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1"><span class="co">#same as</span></a>
<a class="sourceLine" id="cb214-2" title="2">intercept=<span class="dv">3</span><span class="op">+</span><span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;a&quot;</span>,<span class="dv">5</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;b&quot;</span>,<span class="dv">8</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">10</span>,<span class="dv">12</span>)))</a>
<a class="sourceLine" id="cb214-3" title="3">slope=xs<span class="op">*</span>(<span class="dv">4</span><span class="op">+</span><span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;a&quot;</span>,<span class="fl">0.2</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;b&quot;</span>,<span class="fl">0.5</span>,<span class="kw">ifelse</span>(type<span class="op">==</span><span class="st">&quot;c&quot;</span>,<span class="dv">1</span>,<span class="dv">2</span>))))</a>
<a class="sourceLine" id="cb214-4" title="4">ys=slope<span class="op">+</span>intercept<span class="op">+</span><span class="kw">rnorm</span>(<span class="dv">200</span>,<span class="dv">0</span>,<span class="dv">4</span>)</a></code></pre></div>
<p>We can look at the data</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb215-2" title="2"><span class="kw">plot</span>(xs,ys,<span class="dt">col=</span>cores)</a>
<a class="sourceLine" id="cb215-3" title="3"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb215-4" title="4"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb215-5" title="5"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb215-6" title="6"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>As before, it is actually not that easy to confirm the slopes and intercepts are different, as the intercept is not shown in the above plot. We can zoom out the plot and force that</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1"><span class="kw">plot</span>(xs,ys,<span class="dt">col=</span>cores,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">150</span>))</a>
<a class="sourceLine" id="cb216-2" title="2"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb216-3" title="3"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb216-4" title="4"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb216-5" title="5"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb216-6" title="6"><span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">c</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">5</span>,<span class="dv">3</span><span class="op">+</span><span class="dv">8</span>,<span class="dv">3</span><span class="op">+</span><span class="dv">10</span>,<span class="dv">3</span><span class="op">+</span><span class="dv">12</span>),<span class="dt">v=</span><span class="dv">0</span>,<span class="dt">col=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>),<span class="dt">lty=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p>Now, we implement the ANCOVA linear model, but with an <em>interaction</em> term!</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" title="1">lm.ancova2=<span class="kw">lm</span>(ys<span class="op">~</span>xs<span class="op">+</span>type<span class="op">+</span>xs<span class="op">*</span>type)</a>
<a class="sourceLine" id="cb217-2" title="2">sum.lm.ancova2=<span class="kw">summary</span>(lm.ancova2)</a></code></pre></div>
<p>and we look at the output of the model</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" title="1">sum.lm.ancova2</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs + type + xs * type)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.2514  -2.7831  -0.2006   3.0000  10.1051 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.0480     3.4994   2.014 0.045397 *  
## xs            4.2667     0.2345  18.198  &lt; 2e-16 ***
## typeb         4.5418     4.6361   0.980 0.328489    
## typec         3.7997     4.7096   0.807 0.420787    
## typed        15.9380     4.8844   3.263 0.001305 ** 
## xs:typeb      0.1848     0.3160   0.585 0.559468    
## xs:typec      0.8442     0.3103   2.721 0.007106 ** 
## xs:typed      1.2325     0.3203   3.848 0.000162 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.331 on 192 degrees of freedom
## Multiple R-squared:  0.9578,	Adjusted R-squared:  0.9562 
## F-statistic: 622.3 on 7 and 192 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>check how this is an output similar to the ANOVA (implemented via <code>aov</code>, the R function that produces ANOVA tables from expressions akin to linear models)</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" title="1"><span class="kw">summary</span>(<span class="kw">aov</span>(ys<span class="op">~</span>xs<span class="op">+</span>type<span class="op">+</span>xs<span class="op">*</span>type))</a></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq  F value   Pr(&gt;F)    
## xs            1  48776   48776 2600.680  &lt; 2e-16 ***
## type          3  32550   10850  578.501  &lt; 2e-16 ***
## xs:type       3    379     126    6.742 0.000239 ***
## Residuals   192   3601      19                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that the overall F statistic from the regression model has an F-statistic of
622.3, with
7 and
192 degrees of freedom. That corresponds to the composite test with the null hypothesis “are all parameters equal to 0”, which in the ANOVA table, is separated in 3 testes, one for each parameter, with 1, 3 and 3 degrees of freedom each. The residual degrees of freedom are naturally the same in all these tests.</p>
<p>The most interesting aspect it that, naturally, we can check the values of the estimated coefficients, and in particular how to estimate the corresponding regression lines per group</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" title="1"><span class="co">#type a</span></a>
<a class="sourceLine" id="cb222-2" title="2">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]</a></code></pre></div>
<pre><code>## (Intercept) 
##    7.048022</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" title="1">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>##       xs 
## 4.266671</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1"><span class="co">#type b</span></a>
<a class="sourceLine" id="cb226-2" title="2">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">3</span>]</a></code></pre></div>
<pre><code>## (Intercept) 
##     11.5898</code></pre>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">6</span>]</a></code></pre></div>
<pre><code>##       xs 
## 4.451449</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" title="1"><span class="co">#type c</span></a>
<a class="sourceLine" id="cb230-2" title="2">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">4</span>]</a></code></pre></div>
<pre><code>## (Intercept) 
##    10.84769</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">7</span>]</a></code></pre></div>
<pre><code>##       xs 
## 5.110884</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1"><span class="co">#type b</span></a>
<a class="sourceLine" id="cb234-2" title="2">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">5</span>]</a></code></pre></div>
<pre><code>## (Intercept) 
##    22.98597</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" title="1">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">8</span>]</a></code></pre></div>
<pre><code>##       xs 
## 5.499171</code></pre>
<p>we can now add these to the earlier plots, to see how well we have estimated the different lines per treatment</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" title="1"><span class="co">#real lines</span></a>
<a class="sourceLine" id="cb238-2" title="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb238-3" title="3"><span class="kw">plot</span>(xs,ys,<span class="dt">col=</span>cores)</a>
<a class="sourceLine" id="cb238-4" title="4"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">5</span>,<span class="dv">4</span><span class="fl">+0.2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb238-5" title="5"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">8</span>,<span class="dv">4</span><span class="fl">+0.5</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb238-6" title="6"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">10</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb238-7" title="7"><span class="kw">abline</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">12</span>,<span class="dv">4</span><span class="op">+</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb238-8" title="8"><span class="co">#estimated lines</span></a>
<a class="sourceLine" id="cb238-9" title="9"><span class="co">#type a</span></a>
<a class="sourceLine" id="cb238-10" title="10"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>],lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb238-11" title="11"><span class="co">#type b</span></a>
<a class="sourceLine" id="cb238-12" title="12"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">3</span>],</a>
<a class="sourceLine" id="cb238-13" title="13">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">6</span>],<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb238-14" title="14"><span class="co">#type c</span></a>
<a class="sourceLine" id="cb238-15" title="15"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">4</span>],</a>
<a class="sourceLine" id="cb238-16" title="16">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">7</span>],<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb238-17" title="17"><span class="co">#type b</span></a>
<a class="sourceLine" id="cb238-18" title="18"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">5</span>],</a>
<a class="sourceLine" id="cb238-19" title="19">lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">8</span>],<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb238-20" title="20"><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="dt">legend =</span> tr,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dt">inset=</span><span class="fl">0.05</span>)</a>
<a class="sourceLine" id="cb238-21" title="21"><span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="dt">legend =</span><span class="kw">paste</span>(<span class="st">&quot;Estimated&quot;</span>,tr),<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dt">inset=</span><span class="fl">0.05</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>Remember, if this was a real analysis, you would not know the truth, so at best, you would be able to see the predicted lines, but not the real lines, just as in the plot below</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb239-1" title="1"><span class="co"># In real life, we only see this</span></a>
<a class="sourceLine" id="cb239-2" title="2"><span class="kw">plot</span>(xs,ys,<span class="dt">col=</span>cores)</a>
<a class="sourceLine" id="cb239-3" title="3"><span class="co">#plot the lines</span></a>
<a class="sourceLine" id="cb239-4" title="4"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>],lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb239-5" title="5"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">3</span>],lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb239-6" title="6"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">4</span>],lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb239-7" title="7"><span class="kw">abline</span>(lm.ancova2<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lm.ancova2<span class="op">$</span>coefficients[<span class="dv">5</span>],lm.ancova2<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb239-8" title="8"><span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="dt">legend =</span><span class="kw">paste</span>(<span class="st">&quot;Estimated&quot;</span>,tr),<span class="dt">lwd=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dt">inset=</span><span class="fl">0.05</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<div id="modeling-a-data-set" class="section level2">
<h2><span class="header-section-number">8.1</span> Modeling a data set</h2>
<p>In a given dataset we might want to know if the interaction is needed or not, or in other words, if the different lines might have different slopes, or not.</p>
<p>We illustrate that with the data set <code>data4lines.csv</code> that we conseidered before (add link here!)</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" title="1">folder&lt;-<span class="st">&quot;extfiles/&quot;</span></a>
<a class="sourceLine" id="cb240-2" title="2"><span class="co">#folder&lt;-&quot;../Aula7 14 10 2020/&quot;</span></a>
<a class="sourceLine" id="cb240-3" title="3">d4l &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="dt">file=</span><span class="kw">paste0</span>(folder,<span class="st">&quot;data4lines.csv&quot;</span>))</a>
<a class="sourceLine" id="cb240-4" title="4">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(d4l)</a></code></pre></div>
<p>And now we fit a model without interaction, as we did before,</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb241-1" title="1"><span class="co">#fit model per group</span></a>
<a class="sourceLine" id="cb241-2" title="2">lmANC&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>z,<span class="dt">data=</span>data4lines)</a>
<a class="sourceLine" id="cb241-3" title="3"><span class="kw">summary</span>(lmANC)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z, data = data4lines)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -90.01 -35.01   2.54  35.51 108.10 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  45.51813   13.83069   3.291  0.00128 ** 
## x             0.39657    0.02516  15.763  &lt; 2e-16 ***
## zb           54.92376   12.11597   4.533 1.28e-05 ***
## zc          128.20339   11.72572  10.934  &lt; 2e-16 ***
## zd           22.82412   10.26509   2.223  0.02787 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 42.5 on 133 degrees of freedom
## Multiple R-squared:  0.7332,	Adjusted R-squared:  0.7252 
## F-statistic: 91.38 on 4 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>and after a model with the interaction term</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb243-1" title="1"><span class="co">#fit model per group, with interaction</span></a>
<a class="sourceLine" id="cb243-2" title="2">lmlinesI&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>z<span class="op">+</span>x<span class="op">:</span>z,<span class="dt">data=</span>data4lines)</a>
<a class="sourceLine" id="cb243-3" title="3"><span class="kw">summary</span>(lmlinesI)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z + x:z, data = data4lines)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -77.569 -15.787   2.848  17.776  60.875 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -84.72064   19.98946  -4.238 4.24e-05 ***
## x             0.69346    0.04380  15.831  &lt; 2e-16 ***
## zb          109.96907   25.87243   4.250 4.04e-05 ***
## zc          187.01780   24.87546   7.518 8.03e-12 ***
## zd          223.27435   21.82006  10.233  &lt; 2e-16 ***
## x:zb         -0.08161    0.06222  -1.312    0.192    
## x:zc         -0.08902    0.05954  -1.495    0.137    
## x:zd         -0.49630    0.04926 -10.075  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 28.09 on 130 degrees of freedom
## Multiple R-squared:  0.8861,	Adjusted R-squared:   0.88 
## F-statistic: 144.5 on 7 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>It seems like, based on AIC, the second model is best! Which makes total sence, since that indeed we had one line for one of the groups (<code>z</code>) that had a different slope! And that is the significant interaction term above, indicating it is different from the slope of group <code>a</code>.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb245-1" title="1"><span class="kw">AIC</span>(lmANC,lmlinesI)</a></code></pre></div>
<pre><code>##          df      AIC
## lmANC     6 1433.414
## lmlinesI  9 1321.927</code></pre>
<p>Now lets go back to the data. Remember a plot we had on this dataset before?</p>
<p>We noted the plot was messy, including the pooled regression (the thick black line), the regressions fitted to independent data sets, one for each species (museums before!) (the solid lines), and the regressions resulting from the model with species as a factor covariate (dotted-dashed lines).</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" title="1"><span class="co">#plot all the data</span></a>
<a class="sourceLine" id="cb247-2" title="2"><span class="kw">plot</span>(y<span class="op">~</span>x,<span class="dt">col=</span><span class="kw">as.numeric</span>(<span class="kw">as.factor</span>(z)),<span class="dt">data=</span>data4lines,<span class="dt">pch=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb247-3" title="3"><span class="co">#completely independet regression lines</span></a>
<a class="sourceLine" id="cb247-4" title="4"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;a&quot;</span>,]),<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb247-5" title="5"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;b&quot;</span>,]),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb247-6" title="6"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;c&quot;</span>,]),<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb247-7" title="7"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;d&quot;</span>,]),<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb247-8" title="8"><span class="co">#these are the wrong lines... why?</span></a>
<a class="sourceLine" id="cb247-9" title="9"><span class="kw">abline</span>(lmlinesG,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb247-10" title="10"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb247-11" title="11"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">3</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb247-12" title="12"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">4</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb247-13" title="13"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">5</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
<p>Now we can remove the independent lines (to clean it up a bit!) and just leave the no interaction model estimated values, then add the estimated lines from the interaction model below. Remember, AIC says it’s the ones from the interactioon model that are the best representation of the data.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" title="1"><span class="co">#plot all the data</span></a>
<a class="sourceLine" id="cb248-2" title="2"><span class="kw">plot</span>(y<span class="op">~</span>x,<span class="dt">col=</span><span class="kw">as.numeric</span>(<span class="kw">as.factor</span>(z)),<span class="dt">data=</span>data4lines,<span class="dt">pch=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb248-3" title="3"><span class="co"># #completely independent regression lines</span></a>
<a class="sourceLine" id="cb248-4" title="4"><span class="co"># abline(lm(y~x,data=data4lines[data4lines$z==&quot;a&quot;,]),col=1,lty=4)</span></a>
<a class="sourceLine" id="cb248-5" title="5"><span class="co"># abline(lm(y~x,data=data4lines[data4lines$z==&quot;b&quot;,]),col=2,lty=4)</span></a>
<a class="sourceLine" id="cb248-6" title="6"><span class="co"># abline(lm(y~x,data=data4lines[data4lines$z==&quot;c&quot;,]),col=3,lty=4)</span></a>
<a class="sourceLine" id="cb248-7" title="7"><span class="co"># abline(lm(y~x,data=data4lines[data4lines$z==&quot;d&quot;,]),col=4,lty=4)</span></a>
<a class="sourceLine" id="cb248-8" title="8"><span class="co"># no interaction lines</span></a>
<a class="sourceLine" id="cb248-9" title="9"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb248-10" title="10"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">3</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb248-11" title="11"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">4</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb248-12" title="12"><span class="kw">abline</span>(lmANC<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmANC<span class="op">$</span>coefficients[<span class="dv">5</span>],lmANC<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb248-13" title="13"><span class="co"># model with interaction lines</span></a>
<a class="sourceLine" id="cb248-14" title="14"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb248-15" title="15"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">3</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">6</span>],<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb248-16" title="16"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">4</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">7</span>],<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb248-17" title="17"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">5</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">8</span>],<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-127-1.png" width="672" /></p>
<p>Likewise, we could compare the lines from independent lines to those of the interaction model.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" title="1"><span class="co">#plot all the data</span></a>
<a class="sourceLine" id="cb249-2" title="2"><span class="kw">plot</span>(y<span class="op">~</span>x,<span class="dt">col=</span><span class="kw">as.numeric</span>(<span class="kw">as.factor</span>(z)),<span class="dt">data=</span>data4lines,<span class="dt">pch=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb249-3" title="3"><span class="co">#completely independent regression lines</span></a>
<a class="sourceLine" id="cb249-4" title="4"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;a&quot;</span>,]),<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb249-5" title="5"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;b&quot;</span>,]),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb249-6" title="6"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;c&quot;</span>,]),<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb249-7" title="7"><span class="kw">abline</span>(<span class="kw">lm</span>(y<span class="op">~</span>x,<span class="dt">data=</span>data4lines[data4lines<span class="op">$</span>z<span class="op">==</span><span class="st">&quot;d&quot;</span>,]),<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb249-8" title="8"><span class="co"># model with interaction lines</span></a>
<a class="sourceLine" id="cb249-9" title="9"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb249-10" title="10"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">3</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">6</span>],<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb249-11" title="11"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">4</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">7</span>],<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb249-12" title="12"><span class="kw">abline</span>(lmlinesI<span class="op">$</span>coefficients[<span class="dv">1</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">5</span>],lmlinesI<span class="op">$</span>coefficients[<span class="dv">2</span>]<span class="op">+</span>lmlinesI<span class="op">$</span>coefficients[<span class="dv">8</span>],<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">5</span>)</a></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p>It is interesting to see that they are not very different, which is perhaps surprising but… actually… not surprising. Both use exaclty 8 parameters to describe the data… it’s the same thing!!! Linear models are cool :)</p>
</div>
<div id="conclusion" class="section level2">
<h2><span class="header-section-number">8.2</span> Conclusion</h2>
<p>The material in this and the last 3 lectures allows you to fully understand the outputs of simple regression models, and to see how some statistical models that you know from other names are just a linear model.</p>
<p>It also helps you understand how the parameter values represent just features of the data and its generating process, and how we can recover estimates of the original relationships between the variables from said set of parameters.</p>
<p>I recommend you explore the code and output above, and that in particular you experiment with changing means (parameter values for the real models), variances (the precision of how you would measure variables) and sample sizes (which gives you an indication of how much information you have to estimate the underlying reality). Understanding the outputs under these new scenarios is fundamental for progressing towards more complex regression models, like GLMs or GAMs, of which the above cases are just particular cases.</p>
<p>Many additional interesting links on linear models exist online. This is just one of them: <a href="https://data-flair.training/blogs/r-linear-regression-tutorial/" class="uri">https://data-flair.training/blogs/r-linear-regression-tutorial/</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="aula10.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-words.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ECOMODbook.pdf", "ECOMODbook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
