<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Regression inside out | Notes for Ecological Modelling</title>
  <meta name="description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Regression inside out | Notes for Ecological Modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Regression inside out | Notes for Ecological Modelling" />
  
  <meta name="twitter:description" content="This is based on Yihui Xie’s a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Tiago A. Marques" />


<meta name="date" content="2024-11-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="handson.html"/>
<link rel="next" href="ttestANOVAasLMs.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="mainintro.html"><a href="mainintro.html"><i class="fa fa-check"></i><b>2</b> Preamble</a></li>
<li class="chapter" data-level="3" data-path="aknowledgments.html"><a href="aknowledgments.html"><i class="fa fa-check"></i><b>3</b> Aknowledgments</a></li>
<li class="chapter" data-level="4" data-path="usingRintro.html"><a href="usingRintro.html"><i class="fa fa-check"></i><b>4</b> Using R</a></li>
<li class="chapter" data-level="5" data-path="prelim.html"><a href="prelim.html"><i class="fa fa-check"></i><b>5</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.1" data-path="prelim.html"><a href="prelim.html#lbtb"><i class="fa fa-check"></i><b>5.1</b> Learning by the book</a></li>
<li class="chapter" data-level="5.2" data-path="prelim.html"><a href="prelim.html#ftpt"><i class="fa fa-check"></i><b>5.2</b> Following the paper trail</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="about-regression.html"><a href="about-regression.html"><i class="fa fa-check"></i><b>6</b> About regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="about-regression.html"><a href="about-regression.html#what-is-a-regression"><i class="fa fa-check"></i><b>6.1</b> What is a regression?</a></li>
<li class="chapter" data-level="6.2" data-path="about-regression.html"><a href="about-regression.html#the-general-linear-model"><i class="fa fa-check"></i><b>6.2</b> The general linear model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="handson.html"><a href="handson.html"><i class="fa fa-check"></i><b>7</b> Hands On Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="handson.html"><a href="handson.html#the-assumptions-are-on-the-residuals-not-the-data"><i class="fa fa-check"></i><b>7.1</b> The assumptions are on the residuals, not the data</a></li>
<li class="chapter" data-level="7.2" data-path="handson.html"><a href="handson.html#conditional-versus-marginal-distribution"><i class="fa fa-check"></i><b>7.2</b> Conditional versus marginal distribution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="RIO.html"><a href="RIO.html"><i class="fa fa-check"></i><b>8</b> Regression inside out</a>
<ul>
<li class="chapter" data-level="8.1" data-path="RIO.html"><a href="RIO.html#implementing-a-regression"><i class="fa fa-check"></i><b>8.1</b> Implementing a regression</a></li>
<li class="chapter" data-level="8.2" data-path="RIO.html"><a href="RIO.html#simulating-regression-data"><i class="fa fa-check"></i><b>8.2</b> Simulating regression data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="RIO.html"><a href="RIO.html#what-is-the-effect-of-increasing-the-error-a-simulation-experiment"><i class="fa fa-check"></i><b>8.2.1</b> What is the effect of increasing the error: a simulation experiment</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="RIO.html"><a href="RIO.html#two-tasks-to-further-understand-regression"><i class="fa fa-check"></i><b>8.3</b> Two tasks to further understand regression</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="RIO.html"><a href="RIO.html#task-1"><i class="fa fa-check"></i><b>8.3.1</b> Task 1</a></li>
<li class="chapter" data-level="8.3.2" data-path="RIO.html"><a href="RIO.html#task-2"><i class="fa fa-check"></i><b>8.3.2</b> Task 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html"><i class="fa fa-check"></i><b>9</b> t-tests and ANOVAs are just linear models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#a-one-sample-t-test-is-the-simplest-possible-linear-model"><i class="fa fa-check"></i><b>9.1</b> A one sample t-test is the simplest possible linear model</a></li>
<li class="chapter" data-level="9.2" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#the-t-test"><i class="fa fa-check"></i><b>9.2</b> The t-test</a></li>
<li class="chapter" data-level="9.3" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#anova"><i class="fa fa-check"></i><b>9.3</b> ANOVA</a></li>
<li class="chapter" data-level="9.4" data-path="ttestANOVAasLMs.html"><a href="ttestANOVAasLMs.html#a-two-way-anova-and-beyhond-ex-task-do-it-yourself"><i class="fa fa-check"></i><b>9.4</b> A two way ANOVA, and beyhond (ex Task: do it yourself!)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html"><i class="fa fa-check"></i><b>10</b> ANCOVA is (also) just a linear model</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#common-slope-different-intercepts-per-treatment"><i class="fa fa-check"></i><b>10.1</b> Common slope, different intercepts per treatment</a></li>
<li class="chapter" data-level="10.2" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#ANCOVAe"><i class="fa fa-check"></i><b>10.2</b> ANCOVA encore</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ANCOVAasLM.html"><a href="ANCOVAasLM.html#same-story-another-spin"><i class="fa fa-check"></i><b>10.2.1</b> Same story, another spin</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html"><i class="fa fa-check"></i><b>11</b> ANCOVA with different slopes: interactions</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#about-interactions"><i class="fa fa-check"></i><b>11.1</b> About interactions</a></li>
<li class="chapter" data-level="11.2" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#task-1-implementing-the-ancova-with-different-slopes"><i class="fa fa-check"></i><b>11.2</b> Task 1 Implementing the ANCOVA with different slopes</a></li>
<li class="chapter" data-level="11.3" data-path="ANCOVAdifslopes.html"><a href="ANCOVAdifslopes.html#task-2-modeling-a-data-set"><i class="fa fa-check"></i><b>11.3</b> Task 2 Modeling a data set</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html"><i class="fa fa-check"></i><b>12</b> Interactions between continous covariates</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#larger-order-interactions"><i class="fa fa-check"></i><b>12.1</b> Larger order interactions</a></li>
<li class="chapter" data-level="12.2" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#conclusion-on-linear-regression"><i class="fa fa-check"></i><b>12.2</b> Conclusion on linear regression</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ContinousInteractions.html"><a href="ContinousInteractions.html#conclusion"><i class="fa fa-check"></i><b>12.2.1</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="LMinPractice.html"><a href="LMinPractice.html"><i class="fa fa-check"></i><b>13</b> Real life examples using linear models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="LMinPractice.html"><a href="LMinPractice.html#rikz-data"><i class="fa fa-check"></i><b>13.1</b> RIKZ data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="MLEs.html"><a href="MLEs.html"><i class="fa fa-check"></i><b>14</b> Class 13: 10 11 2020 Maximum likelihood and all that</a>
<ul>
<li class="chapter" data-level="14.1" data-path="MLEs.html"><a href="MLEs.html#maximizing-a-likelihood-algebraically"><i class="fa fa-check"></i><b>14.1</b> Maximizing a likelihood algebraically</a></li>
<li class="chapter" data-level="14.2" data-path="MLEs.html"><a href="MLEs.html#numerically-maximizing-a-likelihood"><i class="fa fa-check"></i><b>14.2</b> Numerically Maximizing a likelihood</a></li>
<li class="chapter" data-level="14.3" data-path="MLEs.html"><a href="MLEs.html#the-case-of-a-gaussian"><i class="fa fa-check"></i><b>14.3</b> The case of a Gaussian</a></li>
<li class="chapter" data-level="14.4" data-path="MLEs.html"><a href="MLEs.html#the-case-of-a-linear-model"><i class="fa fa-check"></i><b>14.4</b> The case of a linear model</a></li>
<li class="chapter" data-level="14.5" data-path="MLEs.html"><a href="MLEs.html#the-really-interesting-case"><i class="fa fa-check"></i><b>14.5</b> The really interesting case</a></li>
<li class="chapter" data-level="14.6" data-path="MLEs.html"><a href="MLEs.html#likelihood-above-and-beyond"><i class="fa fa-check"></i><b>14.6</b> Likelihood, above and beyond</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="GLMs.html"><a href="GLMs.html"><i class="fa fa-check"></i><b>15</b> An introduction to generalized linear models</a>
<ul>
<li class="chapter" data-level="15.1" data-path="GLMs.html"><a href="GLMs.html#what-are-glms"><i class="fa fa-check"></i><b>15.1</b> What are GLMs</a></li>
<li class="chapter" data-level="15.2" data-path="GLMs.html"><a href="GLMs.html#the-link-function"><i class="fa fa-check"></i><b>15.2</b> The link function</a></li>
<li class="chapter" data-level="15.3" data-path="GLMs.html"><a href="GLMs.html#most-useful-glm-families"><i class="fa fa-check"></i><b>15.3</b> Most useful GLM Families</a></li>
<li class="chapter" data-level="15.4" data-path="GLMs.html"><a href="GLMs.html#an-example-analysis"><i class="fa fa-check"></i><b>15.4</b> An example analysis</a></li>
<li class="chapter" data-level="15.5" data-path="GLMs.html"><a href="GLMs.html#an-example-of-a-glm-as-a-detail-within-a-conceptualization-framework"><i class="fa fa-check"></i><b>15.5</b> An example of a GLM as a detail within a conceptualization framework</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="aula15.html"><a href="aula15.html"><i class="fa fa-check"></i><b>16</b> Class 15: 17 11 2020</a></li>
<li class="chapter" data-level="17" data-path="example-1---deviance.html"><a href="example-1---deviance.html"><i class="fa fa-check"></i><b>17</b> Example 1 - deviance</a></li>
<li class="chapter" data-level="18" data-path="example-2---lagartyos-glm.html"><a href="example-2---lagartyos-glm.html"><i class="fa fa-check"></i><b>18</b> Example 2 - lagartyos GLM</a>
<ul>
<li class="chapter" data-level="18.1" data-path="example-2---lagartyos-glm.html"><a href="example-2---lagartyos-glm.html#example-2"><i class="fa fa-check"></i><b>18.1</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="aula16.html"><a href="aula16.html"><i class="fa fa-check"></i><b>19</b> Class 16: 18 11 2020</a>
<ul>
<li class="chapter" data-level="19.1" data-path="aula16.html"><a href="aula16.html#a-logistic-regression-example"><i class="fa fa-check"></i><b>19.1</b> A logistic regression example</a></li>
<li class="chapter" data-level="19.2" data-path="aula16.html"><a href="aula16.html#titanic-example"><i class="fa fa-check"></i><b>19.2</b> Titanic example</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="aula16.html"><a href="aula16.html#análise-exploratoria-de-dados"><i class="fa fa-check"></i><b>19.2.1</b> Análise Exploratoria de Dados</a></li>
<li class="chapter" data-level="19.2.2" data-path="aula16.html"><a href="aula16.html#modelação"><i class="fa fa-check"></i><b>19.2.2</b> Modelação</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="aula16.html"><a href="aula16.html#about-multicollinearity"><i class="fa fa-check"></i><b>19.3</b> About multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="GLMM.html"><a href="GLMM.html"><i class="fa fa-check"></i><b>20</b> Random effects and mixed models</a></li>
<li class="chapter" data-level="21" data-path="aula18.html"><a href="aula18.html"><i class="fa fa-check"></i><b>21</b> Class 18: 25 11 2020</a>
<ul>
<li class="chapter" data-level="21.1" data-path="aula18.html"><a href="aula18.html#presence-of-bats"><i class="fa fa-check"></i><b>21.1</b> Presence of bats</a></li>
<li class="chapter" data-level="21.2" data-path="aula18.html"><a href="aula18.html#sponges"><i class="fa fa-check"></i><b>21.2</b> Sponges</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="aula18.html"><a href="aula18.html#reading-data-in"><i class="fa fa-check"></i><b>21.2.1</b> Reading data in</a></li>
<li class="chapter" data-level="21.2.2" data-path="aula18.html"><a href="aula18.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>21.2.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="21.2.3" data-path="aula18.html"><a href="aula18.html#modelling"><i class="fa fa-check"></i><b>21.2.3</b> Modelling</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="aula18.html"><a href="aula18.html#extra-glm-stuff"><i class="fa fa-check"></i><b>21.3</b> Extra GLM stuff</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>22</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Ecological Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="RIO" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Regression inside out<a href="RIO.html#RIO" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this section we will look at regression models from different angles. Hopefully, by the end of this section, you will have mastered the linear model and will be able to recognize that several statistical procedures with famous names (like t-tests or ANOVA) are just special cases of the linear model.</p>
<div id="implementing-a-regression" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Implementing a regression<a href="RIO.html#implementing-a-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider a dataset where we have the weight and lengths of lizards, and we are interested in modelling the weight as a function of the length of the available individuals. This will provide us an excuse to look at the different aspects of a linear model and the corresponding output.</p>
<p>The dataset is available as a text file: “lagartos.txt” . We begin by reading the data in “lagartos.txt”, exploring the data and then fitting a simple regression, a linear model, to the data. Just as a detail regarding wording, which reflects what the procedure does, we fit models to data, we do not fit data to models!</p>
<p>We begin by reading the data in</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="RIO.html#cb13-1" tabindex="-1"></a><span class="co">#folder&lt;-&quot;../Aula6 13 10 2020/&quot;</span></span>
<span id="cb13-2"><a href="RIO.html#cb13-2" tabindex="-1"></a>folder<span class="ot">&lt;-</span><span class="st">&quot;extfiles/&quot;</span></span>
<span id="cb13-3"><a href="RIO.html#cb13-3" tabindex="-1"></a>lagartos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file=</span><span class="fu">paste0</span>(folder,<span class="st">&quot;lagartos.txt&quot;</span>), <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb13-4"><a href="RIO.html#cb13-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(lagartos)</span></code></pre></div>
<p>We can see that we have observations over 97 individuals, for which we have recorded both lengths and weights. We can plot the data, being careful to have the response variable, the weights, on the y-axis, and the explanatory variable, the lengths, on the x-axis.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="RIO.html#cb14-1" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso<span class="sc">~</span>comp))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.2-1.png" width="672" /></p>
<p>(tip begins here)</p>
<p>Tip: A common “rookie” mistake is to confuse the defaul R ploting syntax, and mix the two. Note that <code>plot(y~x)</code> is equivalent to <code>plot(x,y)</code> but different from <code>plot(x~y)</code>. The latter is not what you want, ´~´ should be read as “as a function of” and so you must have the response on the left side of the tilde, but by default the first argument to the function plot is the <span class="math inline">\(x\)</span>, usually by convention the explanatory variable. The next figure illustrates the differences, where I don’t set the axis labels so that the consequences are transparent</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="RIO.html#cb15-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb15-2"><a href="RIO.html#cb15-2" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso<span class="sc">~</span>comp))</span>
<span id="cb15-3"><a href="RIO.html#cb15-3" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso,comp))</span>
<span id="cb15-4"><a href="RIO.html#cb15-4" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(comp<span class="sc">~</span>peso))</span>
<span id="cb15-5"><a href="RIO.html#cb15-5" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(comp,peso))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>(tip ends here)</p>
<p>A linear model seems adequate to represent the weights as a function of the lengths. This is not surprising, especially since we simulated the data to be so. We fit a linear model to the data</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="RIO.html#cb16-1" tabindex="-1"></a>lmlag <span class="ot">&lt;-</span> <span class="fu">lm</span>(peso<span class="sc">~</span>comp,<span class="at">data=</span>lagartos)</span>
<span id="cb16-2"><a href="RIO.html#cb16-2" tabindex="-1"></a><span class="fu">summary</span>(lmlag)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = peso ~ comp, data = lagartos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.5199 -1.6961  0.3495  1.7490  4.7127 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 11.72234    0.72299   16.21   &lt;2e-16 ***
## comp         1.20233    0.05402   22.26   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.415 on 95 degrees of freedom
## Multiple R-squared:  0.8391, Adjusted R-squared:  0.8374 
## F-statistic: 495.3 on 1 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>(tip begins here)</p>
<p>Remember that a linear model is just a special generalized linear model (GLM):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="RIO.html#cb18-1" tabindex="-1"></a>glmlag <span class="ot">&lt;-</span> <span class="fu">glm</span>(peso<span class="sc">~</span>comp,<span class="at">data=</span>lagartos,<span class="at">family=</span><span class="fu">gaussian</span>(<span class="at">link=</span><span class="st">&quot;identity&quot;</span>))</span>
<span id="cb18-2"><a href="RIO.html#cb18-2" tabindex="-1"></a><span class="fu">summary</span>(glmlag)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = peso ~ comp, family = gaussian(link = &quot;identity&quot;), 
##     data = lagartos)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 11.72234    0.72299   16.21   &lt;2e-16 ***
## comp         1.20233    0.05402   22.26   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 5.830492)
## 
##     Null deviance: 3441.8  on 96  degrees of freedom
## Residual deviance:  553.9  on 95  degrees of freedom
## AIC: 450.27
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>as we can see the output looks a bit different (after all, <code>lm</code> and <code>glm</code> are different functions!), but the results are exactly the same. This does not prove it, but it illustrates by example that a linear model is just a GLM with a Gaussian response and an <code>identity</code> link function.</p>
<p>Lets use the results from <code>lm</code>, while noting that everything else would be the same.</p>
<p>(tip ends here)</p>
<p>The estimated regression line is</p>
<p><span class="math display">\[weight= a+b \times length\]</span>
or in this case, with the estimated parameter values,</p>
<p><span class="math display">\[ peso =11.72 +1.2 \times comp \]</span></p>
<p>and the estimated R-squared is 0.84. The standard error associated with the model is estimated to be 2.4146. Below we explain in detail what each of these values correspond to, but for now bear in mind that the estimated standard error corresponds to the standard deviation of the residuals of the model, that is, the difference between the observations and the predicted values given the model. The observation we have already as data, those are the <code>peso</code>. We can obtain the predicted <code>peso</code> for each observation with the function <code>predict</code>, but here we do it manually so that we see that the errors are just the observations minus the predictions.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="RIO.html#cb20-1" tabindex="-1"></a><span class="co">#get estimated values</span></span>
<span id="cb20-2"><a href="RIO.html#cb20-2" tabindex="-1"></a>estimated<span class="ot">&lt;-</span><span class="fu">with</span>(lagartos,<span class="fu">summary</span>(lmlag)<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">summary</span>(lmlag)<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">*</span>comp)</span>
<span id="cb20-3"><a href="RIO.html#cb20-3" tabindex="-1"></a><span class="co"># note this would be the same as</span></span>
<span id="cb20-4"><a href="RIO.html#cb20-4" tabindex="-1"></a><span class="co"># estimated&lt;-predict(lmlag)</span></span></code></pre></div>
<p>Now we can compute the residuals and their corresponding standard error</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="RIO.html#cb21-1" tabindex="-1"></a><span class="co">#get residuals</span></span>
<span id="cb21-2"><a href="RIO.html#cb21-2" tabindex="-1"></a><span class="co">#erros = observações - valores previstos</span></span>
<span id="cb21-3"><a href="RIO.html#cb21-3" tabindex="-1"></a><span class="co"># e= y- (a+bx)</span></span>
<span id="cb21-4"><a href="RIO.html#cb21-4" tabindex="-1"></a><span class="co"># y= (a+bx) + e</span></span>
<span id="cb21-5"><a href="RIO.html#cb21-5" tabindex="-1"></a>resid<span class="ot">&lt;-</span>lagartos<span class="sc">$</span>peso<span class="sc">-</span>estimated</span>
<span id="cb21-6"><a href="RIO.html#cb21-6" tabindex="-1"></a><span class="fu">sd</span>(resid)</span></code></pre></div>
<pre><code>## [1] 2.402032</code></pre>
<p>Note as <code>predict</code>, we could use just the function <code>residuals</code> with the model object as argument to get us the residuals in a single line of code.</p>
<p>The reason the above standard error is not exactly the same as in the model output above has to do with the degrees of freedom, a concept that is hard to explain in this applied context, but relates to the number of available independent bits of information available. So trust me when I say that we loose a degree of freedom for each parameter estimated in a model. The exact value of the standard deviation as estimated in the model must account for that loss of one extra degree of freedom (associated with estimating the slope of the line), and so the standard formula of the <code>sd</code> needs to be adjusted for the lost degree of freedom, like this:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="RIO.html#cb23-1" tabindex="-1"></a><span class="co">#Residual Standard error (Like Standard Deviation)</span></span>
<span id="cb23-2"><a href="RIO.html#cb23-2" tabindex="-1"></a><span class="co">#the right way</span></span>
<span id="cb23-3"><a href="RIO.html#cb23-3" tabindex="-1"></a><span class="co">#Subtract one to ignore intercept</span></span>
<span id="cb23-4"><a href="RIO.html#cb23-4" tabindex="-1"></a>k<span class="ot">=</span><span class="fu">length</span>(lmlag<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span> </span>
<span id="cb23-5"><a href="RIO.html#cb23-5" tabindex="-1"></a><span class="co">#get the error sum of squares</span></span>
<span id="cb23-6"><a href="RIO.html#cb23-6" tabindex="-1"></a>SSE<span class="ot">=</span><span class="fu">sum</span>(lmlag<span class="sc">$</span>residuals<span class="sc">**</span><span class="dv">2</span>)</span>
<span id="cb23-7"><a href="RIO.html#cb23-7" tabindex="-1"></a><span class="co">#Residual Standard Error</span></span>
<span id="cb23-8"><a href="RIO.html#cb23-8" tabindex="-1"></a><span class="fu">sqrt</span>(SSE<span class="sc">/</span>(n<span class="sc">-</span>(<span class="dv">1</span><span class="sc">+</span>k))) </span></code></pre></div>
<pre><code>## [1] 2.414641</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="RIO.html#cb25-1" tabindex="-1"></a><span class="co">#equivalently</span></span>
<span id="cb25-2"><a href="RIO.html#cb25-2" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">var</span>(resid)<span class="sc">*</span>(n<span class="dv">-1</span>)<span class="sc">/</span>(n<span class="dv">-2</span>))</span></code></pre></div>
<pre><code>## [1] 2.414641</code></pre>
<p>Now we get the exact same value as above: 2.415.</p>
<p>The <code>summary</code> of the model above is very useful, but nothing like adding the estimated model to the plot with the data. We can easily add the line to the plot with function <code>abline</code></p>
<p>(tip begins here)</p>
<p>The <code>ab</code> in <code>abline</code> corresponds simply to the <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> in <span class="math inline">\(y=a+bx\)</span>, but the function <code>abline</code> is “smart” enough to take other arguments than just an intercept and slope a slope as arguments. It can take</p>
<ul>
<li>an object of class <code>lm</code> and extract the corresponding <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> for plotting</li>
<li>argument <code>v</code> to add vertical line(s) to an existing plot (e.g. <code>v=20</code> would add a vertical line at <code>x=20</code> to an existing plot)</li>
<li>argument <code>h</code> to add horizontal line(s) to an existing plot (e.g. <code>h=10</code> would add a horizontal line at <code>y=10</code> to an existing plot)</li>
</ul>
<p>(tip ends here)</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="RIO.html#cb27-1" tabindex="-1"></a><span class="co">#with(lagartos,plot(peso~comp))</span></span>
<span id="cb27-2"><a href="RIO.html#cb27-2" tabindex="-1"></a><span class="fu">plot</span>(peso<span class="sc">~</span>comp,<span class="at">data=</span>lagartos)</span>
<span id="cb27-3"><a href="RIO.html#cb27-3" tabindex="-1"></a><span class="co">#these next 3 lines are equivalent</span></span>
<span id="cb27-4"><a href="RIO.html#cb27-4" tabindex="-1"></a><span class="fu">abline</span>(lmlag,<span class="at">col=</span><span class="st">&quot;orange&quot;</span>)</span>
<span id="cb27-5"><a href="RIO.html#cb27-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="fl">11.72234</span>,<span class="at">b=</span><span class="fl">1.20233</span>,<span class="at">col=</span><span class="st">&quot;pink&quot;</span>)</span>
<span id="cb27-6"><a href="RIO.html#cb27-6" tabindex="-1"></a><span class="co"># y = a + bx</span></span>
<span id="cb27-7"><a href="RIO.html#cb27-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="fu">summary</span>(lmlag)<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="dv">1</span>],<span class="at">b=</span><span class="fu">summary</span>(lmlag)<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="dv">1</span>],<span class="at">col=</span><span class="st">&quot;brown&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.9-1.png" width="672" /></p>
<p>Note the last line works because the parameter estimates are hold in a component of the <code>summary</code> of the fitted model called <code>coefficients</code></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="RIO.html#cb28-1" tabindex="-1"></a><span class="fu">summary</span>(lmlag)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##              Estimate Std. Error  t value     Pr(&gt;|t|)
## (Intercept) 11.722343 0.72299153 16.21367 4.135172e-29
## comp         1.202333 0.05402397 22.25555 1.839784e-39</code></pre>
<p>Additionally, we can also add the residuals in the plot (we use the very handy function <code>segments</code>, that adds segments to existing plots, to do so)</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="RIO.html#cb30-1" tabindex="-1"></a><span class="co"># get estimated/predicted values with function residuals</span></span>
<span id="cb30-2"><a href="RIO.html#cb30-2" tabindex="-1"></a>estimated2<span class="ot">&lt;-</span><span class="fu">predict</span>(lmlag)</span>
<span id="cb30-3"><a href="RIO.html#cb30-3" tabindex="-1"></a><span class="co">#plot the data</span></span>
<span id="cb30-4"><a href="RIO.html#cb30-4" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso<span class="sc">~</span>comp,<span class="at">pch=</span><span class="dv">21</span>,<span class="at">bg=</span><span class="st">&quot;brown&quot;</span>,<span class="at">col=</span><span class="st">&quot;green&quot;</span>))</span>
<span id="cb30-5"><a href="RIO.html#cb30-5" tabindex="-1"></a><span class="fu">abline</span>(lmlag,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb30-6"><a href="RIO.html#cb30-6" tabindex="-1"></a><span class="co">#add residuals</span></span>
<span id="cb30-7"><a href="RIO.html#cb30-7" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">segments</span>(<span class="at">x0 =</span> comp,<span class="at">y0 =</span> peso, <span class="at">x1=</span> comp, <span class="at">y1=</span>estimated,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.11-1.png" width="672" /></p>
<p>The regression line corresponds to the line that minimizes the sum of the red distances in the plot above. That is also why it is called a minimum squares line in the special case of a Gaussian model (in PT, é a reta dos mínimos quadrados).</p>
<p>The residuals should, if the model is reasonable - and here that should be the case, as we are using simulated data - be well approximated by a Gaussian distribution. Note we can get the values of the residuals by the difference between the observations and the estimated values, as we did above, or just use the function <code>resid</code> over a fitted model, for simplicity. We can look at an histogram of the residuals below</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="RIO.html#cb31-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb31-2"><a href="RIO.html#cb31-2" tabindex="-1"></a><span class="fu">hist</span>(resid,<span class="at">main=</span><span class="st">&quot;Residuals by hand&quot;</span>,<span class="at">freq=</span><span class="cn">FALSE</span>)</span>
<span id="cb31-3"><a href="RIO.html#cb31-3" tabindex="-1"></a><span class="co">#adding the theorethical density of a Gaussian with mean 0 and the</span></span>
<span id="cb31-4"><a href="RIO.html#cb31-4" tabindex="-1"></a><span class="co">#correct standard error</span></span>
<span id="cb31-5"><a href="RIO.html#cb31-5" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">8</span>,<span class="dv">8</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">8</span>,<span class="dv">8</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="fu">summary</span>(lmlag)<span class="sc">$</span>sigma))</span>
<span id="cb31-6"><a href="RIO.html#cb31-6" tabindex="-1"></a></span>
<span id="cb31-7"><a href="RIO.html#cb31-7" tabindex="-1"></a>resid2<span class="ot">&lt;-</span><span class="fu">residuals</span>(lmlag)</span>
<span id="cb31-8"><a href="RIO.html#cb31-8" tabindex="-1"></a><span class="fu">hist</span>(resid2,<span class="at">main=</span><span class="st">&quot;Residuals by function residuals&quot;</span>)</span>
<span id="cb31-9"><a href="RIO.html#cb31-9" tabindex="-1"></a></span>
<span id="cb31-10"><a href="RIO.html#cb31-10" tabindex="-1"></a><span class="co">#correct standard error</span></span>
<span id="cb31-11"><a href="RIO.html#cb31-11" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">8</span>,<span class="dv">8</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">8</span>,<span class="dv">8</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="fu">summary</span>(lmlag)<span class="sc">$</span>sigma))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.12-1.png" width="672" /></p>
<p>It is often said that the <span class="math inline">\(R^2\)</span> represents the amount of variation in the response that the regression explains, and we are now in a position to illustrate exactly why that is the case. If you assume that all the variability in the response data, the <span class="math inline">\(y_i\)</span>, as the difference between the data points and a common mean</p>
<p><span class="math display">\[\sum_{i=1}^n (y_i- \bar y)^2\]</span>
in an image, the sum of the square of these quantities</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="RIO.html#cb32-1" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb32-2"><a href="RIO.html#cb32-2" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso<span class="sc">~</span>comp))</span>
<span id="cb32-3"><a href="RIO.html#cb32-3" tabindex="-1"></a><span class="fu">abline</span>(lmlag,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb32-4"><a href="RIO.html#cb32-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(lagartos<span class="sc">$</span>peso))</span>
<span id="cb32-5"><a href="RIO.html#cb32-5" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">segments</span>(<span class="at">x0 =</span> comp,<span class="at">y0 =</span> peso, <span class="at">x1=</span> comp, <span class="at">y1=</span><span class="fu">mean</span>(peso),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.14-1.png" width="672" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="RIO.html#cb33-1" tabindex="-1"></a>all.var<span class="ot">&lt;-</span><span class="fu">sum</span>((lagartos<span class="sc">$</span>peso<span class="sc">-</span><span class="fu">mean</span>(lagartos<span class="sc">$</span>peso))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-2"><a href="RIO.html#cb33-2" tabindex="-1"></a>all.var</span></code></pre></div>
<pre><code>## [1] 3441.795</code></pre>
<p>and the variability that is not explained is the one that remains in the errors - for which the corresponding plot illustrating the concept geometrically was shown above, that is</p>
<p><span class="math display">\[\sum_{i=1}^n (y_i- \hat y_i)^2\]</span></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="RIO.html#cb35-1" tabindex="-1"></a>error.var<span class="ot">&lt;-</span><span class="fu">sum</span>((lagartos<span class="sc">$</span>peso<span class="sc">-</span>estimated)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-2"><a href="RIO.html#cb35-2" tabindex="-1"></a>error.var</span></code></pre></div>
<pre><code>## [1] 553.8968</code></pre>
<p>then the ratio of those two quantities is what is not explained by the regression model, and therefore, 1 minus that is what explained by the regression model:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="RIO.html#cb37-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>error.var<span class="sc">/</span>all.var</span></code></pre></div>
<pre><code>## [1] 0.8390675</code></pre>
<p>And that… as noted above… is the <span class="math inline">\(R^2\)</span>=0.8391. This comes from the fact that all of the variability in the data (the <span class="math inline">\(y\)</span>, the response, here the <code>peso</code>) can be decomposed into the variability explained by the model, and the unexplained variability, that of the errors. In a formula</p>
<p><span class="math display">\[SS_{TOTAL}=SS_{REGRESSÃO}+SS_{ERRO}\]</span></p>
<p>Note naturally we could also represent in an image what is explained by the regression model, which is</p>
<p><span class="math display">\[\sum_{i=1}^n (\hat y_i- \bar y)^2\]</span></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="RIO.html#cb39-1" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb39-2"><a href="RIO.html#cb39-2" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">plot</span>(peso<span class="sc">~</span>comp))</span>
<span id="cb39-3"><a href="RIO.html#cb39-3" tabindex="-1"></a><span class="fu">abline</span>(lmlag,<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb39-4"><a href="RIO.html#cb39-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(lagartos<span class="sc">$</span>peso))</span>
<span id="cb39-5"><a href="RIO.html#cb39-5" tabindex="-1"></a><span class="fu">with</span>(lagartos,<span class="fu">segments</span>(<span class="at">x0 =</span> comp,<span class="at">y0 =</span> estimated, <span class="at">x1=</span> comp, <span class="at">y1=</span><span class="fu">mean</span>(peso),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>))</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.18-1.png" width="672" /></p>
<p>and that naturally is obtained as</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="RIO.html#cb40-1" tabindex="-1"></a>reg.var<span class="ot">&lt;-</span><span class="fu">sum</span>((<span class="fu">mean</span>(lagartos<span class="sc">$</span>peso)<span class="sc">-</span>estimated)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb40-2"><a href="RIO.html#cb40-2" tabindex="-1"></a>reg.var</span></code></pre></div>
<pre><code>## [1] 2887.898</code></pre>
<p>and hence the total variability is given by the sum <span class="math inline">\(SS_{REGRESSÃO}+SS_{ERRO}\)</span></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="RIO.html#cb42-1" tabindex="-1"></a>reg.var<span class="sc">+</span>error.var</span></code></pre></div>
<pre><code>## [1] 3441.795</code></pre>
<p>which we had already established to be the total variability in the response</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="RIO.html#cb44-1" tabindex="-1"></a>all.var</span></code></pre></div>
<pre><code>## [1] 3441.795</code></pre>
<p>So, remember that</p>
<p><span class="math display">\[SS_{TOTAL}=SS_{REGRESSÃO}+SS_{ERRO}\]</span></p>
<p>This is something that is often stated without a clear explanation of the reason why that holds. While here I show it by example, it could be easily demonstrated algebraically if one wanted that</p>
<p><span class="math display">\[\sum_{i=1}^n (y_i- \bar y)^2=\sum_{i=1}^n (\hat y_i- \bar y)^2 + \sum_{i=1}^n (y_i- \hat y_i)^2\]</span></p>
<p>If you want to see that that, this 28 minute video shows you the proof: <a href="https://www.youtube.com/watch?v=aQ32qTjqqJM" class="uri">https://www.youtube.com/watch?v=aQ32qTjqqJM</a></p>
<p>I think it could take just 5 minutes ;) but many thanks to Dmitry Leiderman for having it out there! He does it in the context of ANOVA, but ANOVA is just a special case of regression, were you have a continuous response and a single categorical explanatory variable. Therefore, have fun!</p>
</div>
<div id="simulating-regression-data" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Simulating regression data<a href="RIO.html#simulating-regression-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Considering the above example, it should be possible for you to simulate similar data to that we had for the lizards, data assuming that the true relation between the weight and length of a lizard was given by</p>
<p><span class="math display">\[ peso = 12 + 1.2 * comp \]</span></p>
<p>Note that this is a luxury we never have as researchers dealing with real data, knowing what truth is. But creating data from know truth scenarios via simulation can be invaluanble, as it allows us to explore the preformance of methods wehn we know what we should expect from them.</p>
<p>Here we consider that the usual length of a lizard can be between 5 and 20 cm, and the standard error is 4. As in the data we will have 97 lizards.</p>
<p>Then you were told to create the lengths:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="RIO.html#cb46-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">121</span>)</span>
<span id="cb46-2"><a href="RIO.html#cb46-2" tabindex="-1"></a>n<span class="ot">=</span><span class="dv">97</span></span>
<span id="cb46-3"><a href="RIO.html#cb46-3" tabindex="-1"></a><span class="co">#lengths</span></span>
<span id="cb46-4"><a href="RIO.html#cb46-4" tabindex="-1"></a>xs<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">5</span>,<span class="dv">20</span>)</span>
<span id="cb46-5"><a href="RIO.html#cb46-5" tabindex="-1"></a><span class="fu">hist</span>(xs,<span class="at">main=</span><span class="st">&quot;Lenths (cm)&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.21-1.png" width="672" /></p>
<p>and then to create weights of lizards</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="RIO.html#cb47-1" tabindex="-1"></a>a<span class="ot">=</span><span class="dv">12</span></span>
<span id="cb47-2"><a href="RIO.html#cb47-2" tabindex="-1"></a>b<span class="ot">=</span><span class="fl">1.2</span></span>
<span id="cb47-3"><a href="RIO.html#cb47-3" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs</span></code></pre></div>
<p>If we plot the data, all points are in a single line. Why? Because there is no randomness. Given the length of a lizard, we know the weight for sure.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="RIO.html#cb48-1" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.23-1.png" width="672" /></p>
<p>This means that if you try to run a model, it gives you a warning that the model might be unreliable</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="RIO.html#cb49-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs))</span></code></pre></div>
<pre><code>## Warning in summary.lm(lm(ys ~ xs)): essentially perfect fit: summary may be
## unreliable</code></pre>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -5.595e-15 -2.460e-15 -1.878e-15 -1.422e-15  1.873e-13 
## 
## Coefficients:
##              Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept) 1.200e+01  6.050e-15 1.983e+15   &lt;2e-16 ***
## xs          1.200e+00  4.611e-16 2.603e+15   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.934e-14 on 95 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 6.773e+30 on 1 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>reflecting that unlike what the model assumes, there would be no stochasticity in the data.</p>
<p>(tip begins here)</p>
<p>The data stochasticity, or variability, might be induced by process error, i.e. the model might not be perfect, hence not being deterministic as is always the case in nature, but also induced by observation error, e.g. because there is a random error in the measurement of the weights. In practice with a linear model we do not try to separate the two sources of errors, but in more advanced models that might be of interest in itself.</p>
<p>(tip ends here)</p>
<p>Therefore, we make the data realistic, and adhering to the model, by adding some variability to the data, in particular we assume the variability can be represented by Gaussian errors with mean zero and standard deviation of 4 units. Then we plot the data:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="RIO.html#cb52-1" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb52-2"><a href="RIO.html#cb52-2" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.25-1.png" width="672" /></p>
<p>we can now fit a linear model to the data, whic we call <code>lmSimL</code> and explore the results</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="RIO.html#cb53-1" tabindex="-1"></a>SimL<span class="ot">&lt;-</span><span class="fu">data.frame</span>(ys,xs)</span>
<span id="cb53-2"><a href="RIO.html#cb53-2" tabindex="-1"></a>lmSimL<span class="ot">&lt;-</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs,<span class="at">data=</span>SimL)</span>
<span id="cb53-3"><a href="RIO.html#cb53-3" tabindex="-1"></a><span class="fu">summary</span>(lmSimL)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs, data = SimL)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.2024 -2.0587 -0.0304  2.2903  9.6963 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 10.47408    1.05716   9.908  2.6e-16 ***
## xs           1.38463    0.08057  17.186  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.379 on 95 degrees of freedom
## Multiple R-squared:  0.7566, Adjusted R-squared:  0.7541 
## F-statistic: 295.4 on 1 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We can extract from the model the relevant estimated quantities:</p>
<ul>
<li>the intercept is estimated to be 10.4740833 (using <code>coef(lmSimL)[1]</code>),</li>
<li>the slope is estimated to be 1.3846293 (using <code>coef(lmSimL)[2]</code>),</li>
<li>the residual error to be 3.3787165 (using <code>summary(lmSimL)$sigma</code>), and</li>
<li>the <span class="math inline">\(R^2\)</span> to be 0.7566342 (using <code>summary(lmSimL)$r.squared</code>).</li>
</ul>
<p>All the parameters were suitably estimated, not surprising since the amount of error was moderate, reflecting that the <code>xs</code> have a good explanatory power over the <code>ys</code>.</p>
<p>Using the code above, experiment with changing the standard deviation of the error, and see what happens to the estimated <span class="math inline">\(R^2\)</span>, to the parameter estimates, to the estimated error, and to how close the estimated regression model is to the true model.</p>
<p>This is the amazing advantage of a simulation, which we do not have in real data: we know what reality is, and a true model exists!. This will give you a good feeling for what a regression model is and what is does, and what it can’t do. An example of what it can’t give you is reliable estimates when the error is large compared to the systematic part of the model, as illustrated next</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="RIO.html#cb55-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">97</span></span>
<span id="cb55-2"><a href="RIO.html#cb55-2" tabindex="-1"></a><span class="co">#simular comprimentos</span></span>
<span id="cb55-3"><a href="RIO.html#cb55-3" tabindex="-1"></a>comp.sim <span class="ot">&lt;-</span> <span class="fu">runif</span>(n,<span class="dv">5</span>,<span class="dv">20</span>)</span>
<span id="cb55-4"><a href="RIO.html#cb55-4" tabindex="-1"></a>a<span class="ot">&lt;-</span><span class="dv">12</span></span>
<span id="cb55-5"><a href="RIO.html#cb55-5" tabindex="-1"></a>b<span class="ot">&lt;-</span><span class="fl">1.2</span></span>
<span id="cb55-6"><a href="RIO.html#cb55-6" tabindex="-1"></a><span class="co">#simular pesos</span></span>
<span id="cb55-7"><a href="RIO.html#cb55-7" tabindex="-1"></a>peso.sim<span class="ot">&lt;-</span>a<span class="sc">+</span>b<span class="sc">*</span>comp.sim<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb55-8"><a href="RIO.html#cb55-8" tabindex="-1"></a>data.sim<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">csim=</span>comp.sim,<span class="at">psim=</span>peso.sim)</span>
<span id="cb55-9"><a href="RIO.html#cb55-9" tabindex="-1"></a><span class="fu">plot</span>(psim<span class="sc">~</span>csim,<span class="at">data=</span>data.sim)</span>
<span id="cb55-10"><a href="RIO.html#cb55-10" tabindex="-1"></a>mod.sim<span class="ot">&lt;-</span><span class="fu">lm</span>(psim<span class="sc">~</span>csim,<span class="at">data=</span>data.sim)</span>
<span id="cb55-11"><a href="RIO.html#cb55-11" tabindex="-1"></a><span class="fu">abline</span>(mod.sim,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb55-12"><a href="RIO.html#cb55-12" tabindex="-1"></a><span class="fu">summary</span>(mod.sim)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = psim ~ csim, data = data.sim)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3460 -1.1652  0.1329  1.5072  3.0036 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 11.70390    0.56783   20.61   &lt;2e-16 ***
## csim         1.20912    0.04325   27.96   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.822 on 95 degrees of freedom
## Multiple R-squared:  0.8916, Adjusted R-squared:  0.8905 
## F-statistic: 781.6 on 1 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="RIO.html#cb57-1" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb57-2"><a href="RIO.html#cb57-2" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;Estimated line&quot;</span>,<span class="st">&quot;True model&quot;</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;green&quot;</span>),<span class="at">lty=</span><span class="dv">1</span>,<span class="at">inset=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.26-1.png" width="672" /></p>
<div id="what-is-the-effect-of-increasing-the-error-a-simulation-experiment" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> What is the effect of increasing the error: a simulation experiment<a href="RIO.html#what-is-the-effect-of-increasing-the-error-a-simulation-experiment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, let’s consider there’s more and less variance. We also add to each plot the real line (that with the true parameter values) and the one with the estimated parameter values.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="RIO.html#cb58-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb58-2"><a href="RIO.html#cb58-2" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb58-3"><a href="RIO.html#cb58-3" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-4"><a href="RIO.html#cb58-4" tabindex="-1"></a>mod1<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-5"><a href="RIO.html#cb58-5" tabindex="-1"></a><span class="fu">abline</span>(mod1,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-6"><a href="RIO.html#cb58-6" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb58-7"><a href="RIO.html#cb58-7" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">2</span>)</span>
<span id="cb58-8"><a href="RIO.html#cb58-8" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-9"><a href="RIO.html#cb58-9" tabindex="-1"></a>mod2<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-10"><a href="RIO.html#cb58-10" tabindex="-1"></a><span class="fu">abline</span>(mod2,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-11"><a href="RIO.html#cb58-11" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb58-12"><a href="RIO.html#cb58-12" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb58-13"><a href="RIO.html#cb58-13" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-14"><a href="RIO.html#cb58-14" tabindex="-1"></a>mod4<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-15"><a href="RIO.html#cb58-15" tabindex="-1"></a><span class="fu">abline</span>(mod4,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-16"><a href="RIO.html#cb58-16" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb58-17"><a href="RIO.html#cb58-17" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">10</span>)</span>
<span id="cb58-18"><a href="RIO.html#cb58-18" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-19"><a href="RIO.html#cb58-19" tabindex="-1"></a>mod10<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-20"><a href="RIO.html#cb58-20" tabindex="-1"></a><span class="fu">abline</span>(mod10,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-21"><a href="RIO.html#cb58-21" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb58-22"><a href="RIO.html#cb58-22" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">20</span>)</span>
<span id="cb58-23"><a href="RIO.html#cb58-23" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-24"><a href="RIO.html#cb58-24" tabindex="-1"></a>mod20<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-25"><a href="RIO.html#cb58-25" tabindex="-1"></a><span class="fu">abline</span>(mod20,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-26"><a href="RIO.html#cb58-26" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb58-27"><a href="RIO.html#cb58-27" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">100</span>)</span>
<span id="cb58-28"><a href="RIO.html#cb58-28" tabindex="-1"></a><span class="fu">plot</span>(xs,ys)</span>
<span id="cb58-29"><a href="RIO.html#cb58-29" tabindex="-1"></a>mod100<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb58-30"><a href="RIO.html#cb58-30" tabindex="-1"></a><span class="fu">abline</span>(mod100,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb58-31"><a href="RIO.html#cb58-31" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.27-1.png" width="672" /></p>
<p>Not surprisingly, as the variance increases, we get data that more and more looks like it is not coming from a real linear process.</p>
<p>You can also look at the model summaries, and there you can see that, in fact, the models become essentially useless as the variance increases! You can see that both from the correlation, but also by the predictions generated from the model (comparing to the truth), and also the significance of the coefficients associated with the regression parameters.</p>
<p>Make no mistake, the reality is always the same, in terms of the fixed part of the model, it is just the variance that we observe reality with that increases. This could happen either because the model is not adequate (e.g. there are other variables than just length that explain the weight) but also because the measurement error in the weights might be larger (e.g. think about measuring the weight of whales, instead that of lizards, say).</p>
<p>Also, do not get confused, the different green lines might look different, but they are always exactly the same line, the same true model is constant across all plots! You can check that by forcing the y axis to span the same limits.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="RIO.html#cb59-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb59-2"><a href="RIO.html#cb59-2" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb59-3"><a href="RIO.html#cb59-3" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-4"><a href="RIO.html#cb59-4" tabindex="-1"></a>mod1<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-5"><a href="RIO.html#cb59-5" tabindex="-1"></a><span class="fu">abline</span>(mod1,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-6"><a href="RIO.html#cb59-6" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb59-7"><a href="RIO.html#cb59-7" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">2</span>)</span>
<span id="cb59-8"><a href="RIO.html#cb59-8" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-9"><a href="RIO.html#cb59-9" tabindex="-1"></a>mod2<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-10"><a href="RIO.html#cb59-10" tabindex="-1"></a><span class="fu">abline</span>(mod2,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-11"><a href="RIO.html#cb59-11" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb59-12"><a href="RIO.html#cb59-12" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb59-13"><a href="RIO.html#cb59-13" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-14"><a href="RIO.html#cb59-14" tabindex="-1"></a>mod4<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-15"><a href="RIO.html#cb59-15" tabindex="-1"></a><span class="fu">abline</span>(mod4,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-16"><a href="RIO.html#cb59-16" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb59-17"><a href="RIO.html#cb59-17" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">10</span>)</span>
<span id="cb59-18"><a href="RIO.html#cb59-18" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-19"><a href="RIO.html#cb59-19" tabindex="-1"></a>mod10<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-20"><a href="RIO.html#cb59-20" tabindex="-1"></a><span class="fu">abline</span>(mod10,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-21"><a href="RIO.html#cb59-21" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb59-22"><a href="RIO.html#cb59-22" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">20</span>)</span>
<span id="cb59-23"><a href="RIO.html#cb59-23" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-24"><a href="RIO.html#cb59-24" tabindex="-1"></a>mod20<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-25"><a href="RIO.html#cb59-25" tabindex="-1"></a><span class="fu">abline</span>(mod20,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-26"><a href="RIO.html#cb59-26" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb59-27"><a href="RIO.html#cb59-27" tabindex="-1"></a>ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">100</span>)</span>
<span id="cb59-28"><a href="RIO.html#cb59-28" tabindex="-1"></a><span class="fu">plot</span>(xs,ys,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">400</span>,<span class="dv">400</span>))</span>
<span id="cb59-29"><a href="RIO.html#cb59-29" tabindex="-1"></a>mod100<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb59-30"><a href="RIO.html#cb59-30" tabindex="-1"></a><span class="fu">abline</span>(mod100,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb59-31"><a href="RIO.html#cb59-31" tabindex="-1"></a><span class="fu">abline</span>(a,b,<span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.28-1.png" width="672" /></p>
<p>but since then you loose all the ability to look at the actual data in some of the plots, that representation is not really that useful!</p>
<p>Below we tabulate the summary statistics for of each model with increasing variance, focusing on the estimated values for the parameters, their corresponding variances and the <span class="math inline">\(R^2\)</span>.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="RIO.html#cb60-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb60-2"><a href="RIO.html#cb60-2" tabindex="-1"></a>model.stats<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">error=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">100</span>),<span class="at">intercept=</span><span class="cn">NA</span>,<span class="at">ise=</span><span class="cn">NA</span>,<span class="at">slope=</span><span class="cn">NA</span>,<span class="at">sse=</span><span class="cn">NA</span>,<span class="at">sde=</span><span class="cn">NA</span>,<span class="at">R2=</span><span class="cn">NA</span>)</span>
<span id="cb60-3"><a href="RIO.html#cb60-3" tabindex="-1"></a>model.stats[<span class="dv">1</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod1))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod1))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod1)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared)</span>
<span id="cb60-4"><a href="RIO.html#cb60-4" tabindex="-1"></a>model.stats[<span class="dv">2</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod2))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod2))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod2)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared)</span>
<span id="cb60-5"><a href="RIO.html#cb60-5" tabindex="-1"></a>model.stats[<span class="dv">3</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod4))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod4))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod1)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared)</span>
<span id="cb60-6"><a href="RIO.html#cb60-6" tabindex="-1"></a>model.stats[<span class="dv">4</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod10))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod10))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod1)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod10)<span class="sc">$</span>r.squared)</span>
<span id="cb60-7"><a href="RIO.html#cb60-7" tabindex="-1"></a>model.stats[<span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod20))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod20))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod1)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod20)<span class="sc">$</span>r.squared)</span>
<span id="cb60-8"><a href="RIO.html#cb60-8" tabindex="-1"></a>model.stats[<span class="dv">6</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(mod100))[<span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">coef</span>(<span class="fu">summary</span>(mod100))[<span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">summary</span>(mod1)<span class="sc">$</span>sigma,<span class="fu">summary</span>(mod100)<span class="sc">$</span>r.squared)</span>
<span id="cb60-9"><a href="RIO.html#cb60-9" tabindex="-1"></a><span class="fu">kable</span>(model.stats,<span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">error</th>
<th align="right">intercept</th>
<th align="right">ise</th>
<th align="right">slope</th>
<th align="right">sse</th>
<th align="right">sde</th>
<th align="right">R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">12.25</td>
<td align="right">0.34</td>
<td align="right">1.19</td>
<td align="right">0.03</td>
<td align="right">1.08</td>
<td align="right">0.96</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">11.23</td>
<td align="right">0.67</td>
<td align="right">1.26</td>
<td align="right">0.05</td>
<td align="right">2.13</td>
<td align="right">0.87</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="right">12.94</td>
<td align="right">1.26</td>
<td align="right">1.12</td>
<td align="right">0.10</td>
<td align="right">1.08</td>
<td align="right">0.59</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">12.19</td>
<td align="right">3.01</td>
<td align="right">1.21</td>
<td align="right">0.23</td>
<td align="right">1.08</td>
<td align="right">0.23</td>
</tr>
<tr class="odd">
<td align="right">20</td>
<td align="right">9.24</td>
<td align="right">6.40</td>
<td align="right">1.67</td>
<td align="right">0.49</td>
<td align="right">1.08</td>
<td align="right">0.11</td>
</tr>
<tr class="even">
<td align="right">100</td>
<td align="right">41.65</td>
<td align="right">30.10</td>
<td align="right">-0.55</td>
<td align="right">2.29</td>
<td align="right">1.08</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<p>As an example, we can plot the <span class="math inline">\(R^2\)</span> as a function of the variance</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="RIO.html#cb61-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">100</span>),<span class="fu">c</span>(<span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared,<span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared,<span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared,<span class="fu">summary</span>(mod10)<span class="sc">$</span>r.squared,<span class="fu">summary</span>(mod20)<span class="sc">$</span>r.squared,<span class="fu">summary</span>(mod100)<span class="sc">$</span>r.squared),<span class="at">xlab=</span><span class="st">&quot;R^2&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Standard deviation of the error&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.30-1.png" width="672" /></p>
<p>That is quite interesting actually. There seems to be a nonlinear relationship, but we only have a sample size of six different standard deviations, i.e., variances, as variance is standard deviation squared, so it is hard to tell. But we can bring in the power of a <code>for</code> loop to do this for us for many values of the errors. We can then plot the results:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="RIO.html#cb62-1" tabindex="-1"></a>sds<span class="ot">=</span><span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="dv">100</span>,<span class="at">by=</span><span class="fl">0.5</span>)</span>
<span id="cb62-2"><a href="RIO.html#cb62-2" tabindex="-1"></a>nsds<span class="ot">=</span><span class="fu">length</span>(sds)</span>
<span id="cb62-3"><a href="RIO.html#cb62-3" tabindex="-1"></a><span class="co">#an object to hold the correlations</span></span>
<span id="cb62-4"><a href="RIO.html#cb62-4" tabindex="-1"></a>Rsqs<span class="ot">=</span><span class="fu">numeric</span>(nsds)</span>
<span id="cb62-5"><a href="RIO.html#cb62-5" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsds){</span>
<span id="cb62-6"><a href="RIO.html#cb62-6" tabindex="-1"></a>  <span class="co">#create data</span></span>
<span id="cb62-7"><a href="RIO.html#cb62-7" tabindex="-1"></a>  ys<span class="ot">=</span>a<span class="sc">+</span>b<span class="sc">*</span>xs<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,sds[i])</span>
<span id="cb62-8"><a href="RIO.html#cb62-8" tabindex="-1"></a>  <span class="co">#estimate model</span></span>
<span id="cb62-9"><a href="RIO.html#cb62-9" tabindex="-1"></a>  modi<span class="ot">=</span><span class="fu">lm</span>(ys<span class="sc">~</span>xs)</span>
<span id="cb62-10"><a href="RIO.html#cb62-10" tabindex="-1"></a>  <span class="co">#get R-squared</span></span>
<span id="cb62-11"><a href="RIO.html#cb62-11" tabindex="-1"></a>  Rsqs[i]<span class="ot">=</span><span class="fu">summary</span>(modi)<span class="sc">$</span>r.squared</span>
<span id="cb62-12"><a href="RIO.html#cb62-12" tabindex="-1"></a>}</span>
<span id="cb62-13"><a href="RIO.html#cb62-13" tabindex="-1"></a><span class="co">#and at the end... plot results</span></span>
<span id="cb62-14"><a href="RIO.html#cb62-14" tabindex="-1"></a><span class="fu">plot</span>(sds,Rsqs)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.31-1.png" width="672" /></p>
<p>How cool is that! There seems to be evidence of a clear pattern, as anticipated. There is noise in the relation, and that comes because at each iteration there is randomness in the simulated data. Can you think of a way to reduce the noise in the pattern shown? If so, do it yourself!</p>
<p>This means we can model the <span class="math inline">\(R^2\)</span> as a function of the original variance! But we would not be able to model it using a linear model. While you are supposed to know about this yet, generalized linear models, which can be implemented with the help of function <code>gam</code> in package <code>mgcv</code> can come to our help. Later on we will earn more about GAM’s, but for now you can take a look at Noam Ross’s outstanding online free course on them (<a href="https://noamross.github.io/gams-in-r-course/" class="uri">https://noamross.github.io/gams-in-r-course/</a>) if you can’t wait for it.</p>
<p>Here I will just use it as is, you might see the syntax is quite similar to that of the <code>lm</code> function, we simply add syntax to reflect that we have non-linear, smooth terms of covariates (say e.g. <code>s(x)</code>).</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="RIO.html#cb63-1" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code></pre></div>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## This is mgcv 1.9-1. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="RIO.html#cb66-1" tabindex="-1"></a>gam1<span class="ot">=</span><span class="fu">gam</span>(Rsqs<span class="sc">~</span><span class="fu">s</span>(sds),<span class="at">link=</span>log)</span>
<span id="cb66-2"><a href="RIO.html#cb66-2" tabindex="-1"></a><span class="co">#make predictions to plot the estimated GAM model</span></span>
<span id="cb66-3"><a href="RIO.html#cb66-3" tabindex="-1"></a>predRsqs<span class="ot">=</span><span class="fu">predict.gam</span>(gam1,<span class="at">newdata =</span> <span class="fu">list</span>(<span class="at">sds=</span>sds),<span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb66-4"><a href="RIO.html#cb66-4" tabindex="-1"></a><span class="fu">plot</span>(sds,Rsqs)</span>
<span id="cb66-5"><a href="RIO.html#cb66-5" tabindex="-1"></a><span class="fu">lines</span>(sds,predRsqs,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.32-1.png" width="672" /></p>
<p>While we have not yet talked about it, intuitively it seems like the model over-fitted to the data. In other words, the model is too much flexible. Therefore, I constrain the GAM to be not as wiggly (while it might sound like a funny made-up word, the “wiggliness” of a GAM is a technical term used even in publications) by changing the argument <code>k</code> which defines the degrees of freedom in the smooth term.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="RIO.html#cb67-1" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb67-2"><a href="RIO.html#cb67-2" tabindex="-1"></a>gam1<span class="ot">=</span><span class="fu">gam</span>(Rsqs<span class="sc">~</span><span class="fu">s</span>(sds,<span class="at">k=</span><span class="dv">3</span>),<span class="at">link=</span>log)</span>
<span id="cb67-3"><a href="RIO.html#cb67-3" tabindex="-1"></a><span class="co">#make predictions to plot the estimated GAM model</span></span>
<span id="cb67-4"><a href="RIO.html#cb67-4" tabindex="-1"></a>predRsqs<span class="ot">=</span><span class="fu">predict.gam</span>(gam1,<span class="at">newdata =</span> <span class="fu">list</span>(<span class="at">sds=</span>sds),<span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb67-5"><a href="RIO.html#cb67-5" tabindex="-1"></a><span class="fu">plot</span>(sds,Rsqs)</span>
<span id="cb67-6"><a href="RIO.html#cb67-6" tabindex="-1"></a><span class="fu">lines</span>(sds,predRsqs,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.33-1.png" width="672" /></p>
<p>That was too much constraining, so now we are under-fitting, the model in not flexible enough to fit the data. We increase the allowed level of wiggliness again</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="RIO.html#cb68-1" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb68-2"><a href="RIO.html#cb68-2" tabindex="-1"></a>gam1<span class="ot">=</span><span class="fu">gam</span>(Rsqs<span class="sc">~</span><span class="fu">s</span>(sds,<span class="at">k=</span><span class="dv">6</span>),<span class="at">link=</span>log)</span>
<span id="cb68-3"><a href="RIO.html#cb68-3" tabindex="-1"></a><span class="co">#make predictions to plot the estimated GAM model</span></span>
<span id="cb68-4"><a href="RIO.html#cb68-4" tabindex="-1"></a>predRsqs<span class="ot">=</span><span class="fu">predict.gam</span>(gam1,<span class="at">newdata =</span> <span class="fu">list</span>(<span class="at">sds=</span>sds),<span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb68-5"><a href="RIO.html#cb68-5" tabindex="-1"></a><span class="fu">plot</span>(sds,Rsqs)</span>
<span id="cb68-6"><a href="RIO.html#cb68-6" tabindex="-1"></a><span class="fu">lines</span>(sds,predRsqs,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a6.34-1.png" width="672" /></p>
<p>but that is already over-fitting… conclusion, the GAM might not be the right tool here :) Perhaps we could consider a model that embeds some understanding about the process between the two quantities, which is presumably possible to achieve by exploring analytically what said relation should be.</p>
<p>Being happy with the visual illustration of the relation and the preview of how the use of a more flexible approach than a linear model might be useful to fit models to data, we will leave that implementation for readers which might find it an interesting (but quite likely to be found non-trivial) exercise.</p>
</div>
</div>
<div id="two-tasks-to-further-understand-regression" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Two tasks to further understand regression<a href="RIO.html#two-tasks-to-further-understand-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we continue exploring regression models, but we are going to increase their complexity. We are no longer just thinking about the simple linear model <code>a+bx</code>, but we add more explanatory variables. In particular, we will also add a factor covariate. And then we look under the hood to understand what that means in practice and how to interpret the regression coefficients.</p>
<p>We do this based on a couple of tasks. Implementing the tasks allows the students to see hands on what is behind the regression model.</p>
<div id="task-1" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Task 1<a href="RIO.html#task-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first task the students were faced was to use some code to explore, by simulation, the impact of having variables in the model that are not relevant to explain the response. In particular, we wanted to identify when there would be no errors, or when there would be type I (a variable not relevant to explain the response is found relevant) and type II (a relevant variable to explain the response is not considered relevant) errors.</p>
<p>For the sake of this example we consider a significance level of 5%, but remember there is nothing sacred about <span class="math inline">\(\alpha=0.05\)</span>. The significance level should be chosen by a researcher given proper consideration of the implications of a type I error in the considered setting.</p>
<p>The guidelines provided were: “Using the code below, and while changing the <code>seed</code> (<code>******</code> to begin with, so the code does not run as is!), explore how changing the parameters and the error leads to different amounts of type I and type II errors.”</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="RIO.html#cb69-1" tabindex="-1"></a><span class="co"># xs1 and xs2 wrong - type II error, xs3 and xs4 ok</span></span>
<span id="cb69-2"><a href="RIO.html#cb69-2" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="er">******</span></span>
<span id="cb69-3"><a href="RIO.html#cb69-3" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb69-4"><a href="RIO.html#cb69-4" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb69-5"><a href="RIO.html#cb69-5" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb69-6"><a href="RIO.html#cb69-6" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb69-7"><a href="RIO.html#cb69-7" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb69-8"><a href="RIO.html#cb69-8" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb69-9"><a href="RIO.html#cb69-9" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb69-10"><a href="RIO.html#cb69-10" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb69-11"><a href="RIO.html#cb69-11" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb69-12"><a href="RIO.html#cb69-12" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb69-13"><a href="RIO.html#cb69-13" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb69-14"><a href="RIO.html#cb69-14" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span>
<span id="cb69-15"><a href="RIO.html#cb69-15" tabindex="-1"></a><span class="co">#a model missing a variable, xs2</span></span>
<span id="cb69-16"><a href="RIO.html#cb69-16" tabindex="-1"></a><span class="co">#summary(lm(ys~xs1))</span></span>
<span id="cb69-17"><a href="RIO.html#cb69-17" tabindex="-1"></a><span class="co">#the true model</span></span>
<span id="cb69-18"><a href="RIO.html#cb69-18" tabindex="-1"></a><span class="co">#summary(lm(ys~xs1+xs2))</span></span>
<span id="cb69-19"><a href="RIO.html#cb69-19" tabindex="-1"></a><span class="co">#a model including irrelevant variables</span></span>
<span id="cb69-20"><a href="RIO.html#cb69-20" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<p>The first thing to notice is that the model we simulate from only includes <code>xs1</code> and <code>xs2</code>. So, <code>xs3</code> and <code>xs4</code> do not have any impact on the response <code>y</code>. In other words, if we find that <code>xs3</code> and/or <code>xs4</code> are relevant to explain the response we have a type I error, as we have identified an effect where there was none. On the other hand, if we do not find <code>xs1</code> and <code>xs2</code> to be relevant to explain the response, we have a type II error, as we failed to identify a real effect.</p>
<p>So we try different values for the seed and check what happens. Let’s just try <code>seed&lt;-1</code></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="RIO.html#cb70-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb70-2"><a href="RIO.html#cb70-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb70-3"><a href="RIO.html#cb70-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb70-4"><a href="RIO.html#cb70-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb70-5"><a href="RIO.html#cb70-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb70-6"><a href="RIO.html#cb70-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb70-7"><a href="RIO.html#cb70-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb70-8"><a href="RIO.html#cb70-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb70-9"><a href="RIO.html#cb70-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb70-10"><a href="RIO.html#cb70-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb70-11"><a href="RIO.html#cb70-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb70-12"><a href="RIO.html#cb70-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb70-13"><a href="RIO.html#cb70-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span>
<span id="cb70-14"><a href="RIO.html#cb70-14" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb70-15"><a href="RIO.html#cb70-15" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<p>All good, no errors. That is, <code>xs1</code> and <code>xs2</code> are considered statistically significant at th 5% level and <code>xs3</code> and <code>xs4</code> are not found relevant to explain the response. Now, we keep changing <code>seed</code></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="RIO.html#cb71-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">4</span></span>
<span id="cb71-2"><a href="RIO.html#cb71-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb71-3"><a href="RIO.html#cb71-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb71-4"><a href="RIO.html#cb71-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb71-5"><a href="RIO.html#cb71-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb71-6"><a href="RIO.html#cb71-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb71-7"><a href="RIO.html#cb71-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb71-8"><a href="RIO.html#cb71-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb71-9"><a href="RIO.html#cb71-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb71-10"><a href="RIO.html#cb71-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb71-11"><a href="RIO.html#cb71-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb71-12"><a href="RIO.html#cb71-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb71-13"><a href="RIO.html#cb71-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span>
<span id="cb71-14"><a href="RIO.html#cb71-14" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb71-15"><a href="RIO.html#cb71-15" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<p>We find our first type I error, <code>xs4</code> is found statistically significant, but we know it has no effect on the response. The same happens with <code>seed</code> being e.g. 9, 10. When we try <code>seed &lt;- 11</code> we get another type I error, this time on <code>xs4</code></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="RIO.html#cb72-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">11</span></span>
<span id="cb72-2"><a href="RIO.html#cb72-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb72-3"><a href="RIO.html#cb72-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb72-4"><a href="RIO.html#cb72-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb72-5"><a href="RIO.html#cb72-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb72-6"><a href="RIO.html#cb72-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb72-7"><a href="RIO.html#cb72-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb72-8"><a href="RIO.html#cb72-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb72-9"><a href="RIO.html#cb72-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb72-10"><a href="RIO.html#cb72-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb72-11"><a href="RIO.html#cb72-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb72-12"><a href="RIO.html#cb72-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb72-13"><a href="RIO.html#cb72-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.4-1.png" width="672" /></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="RIO.html#cb73-1" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb73-2"><a href="RIO.html#cb73-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs1 + xs2 + xs3 + xs4)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.3076  -2.7316   0.3072   2.2102   7.9088 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 16.44303    7.42710   2.214   0.0319 *  
## xs1          2.87327    0.21665  13.262  &lt; 2e-16 ***
## xs2          1.93313    0.25274   7.649 1.12e-09 ***
## xs3         -0.47689    0.22325  -2.136   0.0381 *  
## xs4         -0.08922    0.20937  -0.426   0.6720    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.074 on 45 degrees of freedom
## Multiple R-squared:  0.8484, Adjusted R-squared:  0.8349 
## F-statistic: 62.94 on 4 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>However, even after several runs, we never make a type II error. That must mean this setting has a large power, i.e. the ability to detect a true effect when one exists. Well, there are many ways to decrease power, like having a smaller sample size, increase the error or lower the true effect. Let’s try to increase the error, instead of the 4 used above, let’s pump it up10 fold to 40</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="RIO.html#cb75-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">100</span></span>
<span id="cb75-2"><a href="RIO.html#cb75-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb75-3"><a href="RIO.html#cb75-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb75-4"><a href="RIO.html#cb75-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb75-5"><a href="RIO.html#cb75-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb75-6"><a href="RIO.html#cb75-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb75-7"><a href="RIO.html#cb75-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb75-8"><a href="RIO.html#cb75-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb75-9"><a href="RIO.html#cb75-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb75-10"><a href="RIO.html#cb75-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb75-11"><a href="RIO.html#cb75-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb75-12"><a href="RIO.html#cb75-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb75-13"><a href="RIO.html#cb75-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.5-1.png" width="672" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="RIO.html#cb76-1" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb76-2"><a href="RIO.html#cb76-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs1 + xs2 + xs3 + xs4)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -73.25 -17.86  -6.76  21.25  68.42 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  22.8661    41.3133   0.553    0.583
## xs1           1.6034     1.8564   0.864    0.392
## xs2           0.9163     1.8092   0.506    0.615
## xs3           1.9650     1.6038   1.225    0.227
## xs4          -0.8544     1.7449  -0.490    0.627
## 
## Residual standard error: 32.4 on 45 degrees of freedom
## Multiple R-squared:  0.06896,    Adjusted R-squared:  -0.0138 
## F-statistic: 0.8333 on 4 and 45 DF,  p-value: 0.5112</code></pre>
<p>That was an overkill, now there is so much noise must seeds we use do not allow us to find an effect, let’s cut that in half to 20</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="RIO.html#cb78-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">100</span></span>
<span id="cb78-2"><a href="RIO.html#cb78-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb78-3"><a href="RIO.html#cb78-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb78-4"><a href="RIO.html#cb78-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb78-5"><a href="RIO.html#cb78-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb78-6"><a href="RIO.html#cb78-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb78-7"><a href="RIO.html#cb78-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb78-8"><a href="RIO.html#cb78-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb78-9"><a href="RIO.html#cb78-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb78-10"><a href="RIO.html#cb78-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb78-11"><a href="RIO.html#cb78-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb78-12"><a href="RIO.html#cb78-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb78-13"><a href="RIO.html#cb78-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.6-1.png" width="672" /></p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="RIO.html#cb79-1" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb79-2"><a href="RIO.html#cb79-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs1 + xs2 + xs3 + xs4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.624  -8.927  -3.380  10.623  34.211 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  13.9330    20.6566   0.675    0.503  
## xs1           2.3017     0.9282   2.480    0.017 *
## xs2           1.4582     0.9046   1.612    0.114  
## xs3           0.9825     0.8019   1.225    0.227  
## xs4          -0.4272     0.8724  -0.490    0.627  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.2 on 45 degrees of freedom
## Multiple R-squared:  0.2262, Adjusted R-squared:  0.1574 
## F-statistic: 3.288 on 4 and 45 DF,  p-value: 0.01901</code></pre>
<p>back to all correct. Now, let’s change seed again</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="RIO.html#cb81-1" tabindex="-1"></a>seed<span class="ot">&lt;-</span><span class="dv">103</span></span>
<span id="cb81-2"><a href="RIO.html#cb81-2" tabindex="-1"></a><span class="fu">set.seed</span>(seed)</span>
<span id="cb81-3"><a href="RIO.html#cb81-3" tabindex="-1"></a><span class="co">#define parameters</span></span>
<span id="cb81-4"><a href="RIO.html#cb81-4" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50</span>;b0<span class="ot">&lt;-</span><span class="dv">5</span>;b1<span class="ot">&lt;-</span><span class="dv">3</span>;b2<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">2</span>;error <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb81-5"><a href="RIO.html#cb81-5" tabindex="-1"></a><span class="co">#simulate potential explanatory variables</span></span>
<span id="cb81-6"><a href="RIO.html#cb81-6" tabindex="-1"></a>xs1<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb81-7"><a href="RIO.html#cb81-7" tabindex="-1"></a>xs2<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb81-8"><a href="RIO.html#cb81-8" tabindex="-1"></a>xs3<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb81-9"><a href="RIO.html#cb81-9" tabindex="-1"></a>xs4<span class="ot">=</span><span class="fu">runif</span>(n,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb81-10"><a href="RIO.html#cb81-10" tabindex="-1"></a><span class="co">#simulate response</span></span>
<span id="cb81-11"><a href="RIO.html#cb81-11" tabindex="-1"></a>ys<span class="ot">=</span>b0<span class="sc">+</span>b1<span class="sc">*</span>xs1<span class="sc">-</span>b2<span class="sc">*</span>xs2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">sd=</span>error)</span>
<span id="cb81-12"><a href="RIO.html#cb81-12" tabindex="-1"></a><span class="co">#plot data</span></span>
<span id="cb81-13"><a href="RIO.html#cb81-13" tabindex="-1"></a><span class="fu">plot</span>(xs1,ys)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.7-1.png" width="672" /></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="RIO.html#cb82-1" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb82-2"><a href="RIO.html#cb82-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ys<span class="sc">~</span>xs1<span class="sc">+</span>xs2<span class="sc">+</span>xs3<span class="sc">+</span>xs4))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs1 + xs2 + xs3 + xs4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.079 -10.686  -0.148  16.413  33.845 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  9.70575   33.83339   0.287   0.7755  
## xs1          2.32559    0.93980   2.475   0.0172 *
## xs2          1.97688    1.20464   1.641   0.1078  
## xs3          0.69013    1.02110   0.676   0.5026  
## xs4          0.08031    0.97427   0.082   0.9347  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.6 on 45 degrees of freedom
## Multiple R-squared:  0.1524, Adjusted R-squared:  0.07706 
## F-statistic: 2.023 on 4 and 45 DF,  p-value: 0.1073</code></pre>
<p>Bang on, a type II error, as <code>xs2</code> is no longer considered statistically significant. I am sure you can now play with the relevant model parameters, <code>b1</code>, <code>b2</code>, to incleare and decreese the actual effect, and with sample size <code>n</code> or as above with the <code>error</code> and explore the consequences of changing the balance in effect size, error and sample size on the ability of incurring in errors when doing regression. But remmeber the key, the reason we are able to see if an error is made or not is because we simulated reality. In this case, as it is never the case in an ecological dataset, we know the true model, which was</p>
<p><span class="math display">\[y=\beta_0+\beta_1 xs_1+\beta_2 xs2\]</span></p>
<p>That is the luxury of simulation, allowing you to test scenarios where “reality” is known, hence evaluating methods performance.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="RIO.html#cb84-1" tabindex="-1"></a>folder<span class="ot">&lt;-</span><span class="st">&quot;extfiles/&quot;</span></span>
<span id="cb84-2"><a href="RIO.html#cb84-2" tabindex="-1"></a><span class="co">#folder&lt;-&quot;../Aula7 14 10 2020/&quot;</span></span>
<span id="cb84-3"><a href="RIO.html#cb84-3" tabindex="-1"></a>d4l <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file=</span><span class="fu">paste0</span>(folder,<span class="st">&quot;data4lines.csv&quot;</span>))</span>
<span id="cb84-4"><a href="RIO.html#cb84-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d4l)</span></code></pre></div>
</div>
<div id="task-2" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Task 2<a href="RIO.html#task-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The second task the students were faced was to create some regression data and the explore fitting models to it.</p>
<p><img src="extfiles/Aula7Task7.JPG" /></p>
<p>The data was simulated via this website: <a href="https://drawdata.xyz/" class="uri">https://drawdata.xyz/</a> and was named <code>data4lines.csv</code>. Each student had its own dataset, here I work with my example.</p>
<p>We begin by reading the data in and plot it</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="RIO.html#cb85-1" tabindex="-1"></a><span class="co">#read the data</span></span>
<span id="cb85-2"><a href="RIO.html#cb85-2" tabindex="-1"></a>folder<span class="ot">&lt;-</span><span class="st">&quot;extfiles/&quot;</span></span>
<span id="cb85-3"><a href="RIO.html#cb85-3" tabindex="-1"></a>data4lines <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file=</span><span class="fu">paste0</span>(folder,<span class="st">&quot;data4lines.csv&quot;</span>))</span>
<span id="cb85-4"><a href="RIO.html#cb85-4" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb85-5"><a href="RIO.html#cb85-5" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.9-1.png" width="672" /></p>
<p>Now, to turn this a bit more interesting, we come up with a narrative.</p>
<p>These correspond to observations from weights and lengths of a sample of animals, fish from the species <em>Fishus inventadicus</em>. We could fit a regression line to this data and see if we can predict weight from length</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="RIO.html#cb86-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb86-2"><a href="RIO.html#cb86-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines)</span>
<span id="cb86-3"><a href="RIO.html#cb86-3" tabindex="-1"></a><span class="co">#fit model to pooled data</span></span>
<span id="cb86-4"><a href="RIO.html#cb86-4" tabindex="-1"></a>lmlinesG<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines)</span>
<span id="cb86-5"><a href="RIO.html#cb86-5" tabindex="-1"></a><span class="fu">abline</span>(lmlinesG,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.10-1.png" width="672" /></p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="RIO.html#cb87-1" tabindex="-1"></a><span class="fu">summary</span>(lmlinesG)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = data4lines)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -134.304  -44.188   -1.995   29.432  148.202 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 107.17590   14.03069   7.639 3.51e-12 ***
## x             0.35513    0.03553   9.995  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 61.78 on 136 degrees of freedom
## Multiple R-squared:  0.4235, Adjusted R-squared:  0.4193 
## F-statistic: 99.91 on 1 and 136 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>and it looks like we can indeed predict the weight of the species from its length. The length is highly statistically significant. Not surprisingly, the longer the fish the heavier it is.</p>
<p>Now, the plot thickens. These animals actually came from 4 different museums, and are assumed to be the same species. However, a scientist decides to look at whether there are differences in the data from the 4 museums. So he colors the data by museum</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="RIO.html#cb89-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb89-2"><a href="RIO.html#cb89-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>data4lines,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb89-3"><a href="RIO.html#cb89-3" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">inset=</span><span class="fl">0.05</span>,<span class="at">legend=</span>letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">pch=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.11-1.png" width="672" /></p>
<p>We see a pattern in the data, the data from the different museums tend to cluster. He decides to investigate. Note folks providing names to museum in this country are a bit boring, and the museums are called “a”, “b”, “c” and “d”.</p>
<p>Our smart researcher says: “well, it seems like the relationship might be different in each museum”. Then, maybe I should fit a model that includes museum as a covariate <code>weight~length+museum</code>.</p>
<p><span class="math display">\[y=\beta_0+\beta_1 \times length +\beta_2 \times museum\]</span></p>
<p>And so he does and plots it</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="RIO.html#cb90-1" tabindex="-1"></a><span class="co">#fit model per group</span></span>
<span id="cb90-2"><a href="RIO.html#cb90-2" tabindex="-1"></a>lmlines<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>z,<span class="at">data=</span>data4lines)</span>
<span id="cb90-3"><a href="RIO.html#cb90-3" tabindex="-1"></a><span class="fu">summary</span>(lmlines)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z, data = data4lines)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -90.01 -35.01   2.54  35.51 108.10 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  45.51813   13.83069   3.291  0.00128 ** 
## x             0.39657    0.02516  15.763  &lt; 2e-16 ***
## zb           54.92376   12.11597   4.533 1.28e-05 ***
## zc          128.20339   11.72572  10.934  &lt; 2e-16 ***
## zd           22.82412   10.26509   2.223  0.02787 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 42.5 on 133 degrees of freedom
## Multiple R-squared:  0.7332, Adjusted R-squared:  0.7252 
## F-statistic: 91.38 on 4 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The output shows that the length is relevant, but the museum is relevant too. The relationship might be different per museum! In the output we see the <code>x</code>, the length, but not the <code>z</code>, it has been transformed into <code>zb</code>, <code>zc</code> and <code>zd</code>. Why is that? That is a mystery that we shall unfold now!</p>
<p>While the model we are fitting might be represented by <code>weight~length+museum</code>, the design matrix being fitted replaces the <code>museum</code> (a factor with 4 levels) with 3 dummy variables (a factor with k levels required k-1 dummy variables). So the real model being fitted is really</p>
<p><span class="math display">\[y=\beta_0+\beta_1 \times length + \beta_{2b} \times zb + \beta_{2c} \times zc + \beta_{2d} \times zd\]</span></p>
<p>Wait, but where is the level <code>a</code>? It is in the intercept, and if I had an euro for each time that confused a student, I would not be here but in a beach in the Bahamas having a piña colada :)</p>
<p>But let’s unfold the mistery, shall we? By default, R takes 1 level of (each/a) factor and uses it as the intercept. Here it used <code>a</code> (the choice is in this case by alphabetical ored, but one can change that, which might be useful if e.g. you want to have as the intercept a control level, say; look e.g. into function <code>factor</code> help to see how you can change the baseline <code>level</code> of a factor).</p>
<p>Hence, the intercept for museum <code>a</code> is 45.5181335. What about the intercep of the othe rmuseums? They are always reported with <code>a</code> as the reference. Look at the equation above, what happens when say zc is 1 and zd and zb are 0, it becomes</p>
<p><span class="math display">\[y=\beta_0+\beta_1 \times length + \beta_{2c} \times zc \]</span>
<span class="math display">\[y=(\beta_0+\beta_{2c})+\beta_1 \times length = intercep + slope \times length\]</span></p>
<p>and so, from the above output, that equates to <code>y=lmlines$coefficients[1]+lmlines$coefficients[4],lmlines$coefficients[2]</code> or 173.7215247+0.3965715 <span class="math inline">\(\times\)</span> <code>length</code>.</p>
<p>So now we can add all these estimated regression lines to the plot</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="RIO.html#cb92-1" tabindex="-1"></a><span class="co">#plot all</span></span>
<span id="cb92-2"><a href="RIO.html#cb92-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>data4lines)</span>
<span id="cb92-3"><a href="RIO.html#cb92-3" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">inset=</span><span class="fl">0.05</span>,<span class="at">legend=</span><span class="fu">c</span>(LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="st">&quot;all&quot;</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">1</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">4</span>),<span class="dv">2</span>),<span class="at">lwd=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">4</span>),<span class="dv">3</span>))</span>
<span id="cb92-4"><a href="RIO.html#cb92-4" tabindex="-1"></a><span class="co">#these are the wrong lines... why?</span></span>
<span id="cb92-5"><a href="RIO.html#cb92-5" tabindex="-1"></a><span class="fu">abline</span>(lmlinesG,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb92-6"><a href="RIO.html#cb92-6" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb92-7"><a href="RIO.html#cb92-7" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb92-8"><a href="RIO.html#cb92-8" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb92-9"><a href="RIO.html#cb92-9" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.13-1.png" width="672" /></p>
<p>note that, not surprisingly, all these lines have the same slope. Or in other words, the model we considered assumes that the slope of the model is the same across museums (which, remember, we know if not true!). We can easily check that the intercepts (i.e. where the lines cross when length=x=0) of all lines are indeed easy to get from the model’s output</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="RIO.html#cb93-1" tabindex="-1"></a><span class="co">#plot all</span></span>
<span id="cb93-2"><a href="RIO.html#cb93-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">700</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">450</span>),<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>data4lines)</span>
<span id="cb93-3"><a href="RIO.html#cb93-3" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">inset=</span><span class="fl">0.05</span>,<span class="at">legend=</span><span class="fu">c</span>(LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="st">&quot;all&quot;</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">1</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">4</span>),<span class="dv">2</span>),<span class="at">lwd=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">4</span>),<span class="dv">3</span>))</span>
<span id="cb93-4"><a href="RIO.html#cb93-4" tabindex="-1"></a><span class="co">#these are the wrong lines... why?</span></span>
<span id="cb93-5"><a href="RIO.html#cb93-5" tabindex="-1"></a><span class="fu">abline</span>(lmlinesG,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb93-6"><a href="RIO.html#cb93-6" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb93-7"><a href="RIO.html#cb93-7" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb93-8"><a href="RIO.html#cb93-8" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb93-9"><a href="RIO.html#cb93-9" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">4</span>)</span>
<span id="cb93-10"><a href="RIO.html#cb93-10" tabindex="-1"></a></span>
<span id="cb93-11"><a href="RIO.html#cb93-11" tabindex="-1"></a></span>
<span id="cb93-12"><a href="RIO.html#cb93-12" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb93-13"><a href="RIO.html#cb93-13" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fl">45.51813</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb93-14"><a href="RIO.html#cb93-14" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fl">45.51813+54.92376</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb93-15"><a href="RIO.html#cb93-15" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fl">45.51813+128.20339</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb93-16"><a href="RIO.html#cb93-16" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fl">45.51813+22.82412</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.14-1.png" width="672" /></p>
<p>Now, the smart biologist then says that he could also fit a separate line to each museum’s data. And so he does, and that looks like this:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="RIO.html#cb94-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb94-2"><a href="RIO.html#cb94-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>data4lines,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb94-3"><a href="RIO.html#cb94-3" tabindex="-1"></a><span class="co">#completely independet regression lines</span></span>
<span id="cb94-4"><a href="RIO.html#cb94-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;a&quot;</span>,]),<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb94-5"><a href="RIO.html#cb94-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;b&quot;</span>,]),<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb94-6"><a href="RIO.html#cb94-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;c&quot;</span>,]),<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb94-7"><a href="RIO.html#cb94-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;d&quot;</span>,]),<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb94-8"><a href="RIO.html#cb94-8" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">inset=</span><span class="fl">0.05</span>,<span class="at">legend=</span>letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">pch=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.15-1.png" width="672" /></p>
<p>Naturally, now the lines do not have the same slope, and we can compare all these in a single plot. This plot is really messy, as it includes the pooled regression (the thick black line), the regressions fitted to independent data sets, one for each museum (the solid lines), and the regressions resulting from the model with museum as a factor covariate (dotted-dashed lines).</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="RIO.html#cb95-1" tabindex="-1"></a><span class="co">#plot all the data</span></span>
<span id="cb95-2"><a href="RIO.html#cb95-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x,<span class="at">col=</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(z)),<span class="at">data=</span>data4lines,<span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb95-3"><a href="RIO.html#cb95-3" tabindex="-1"></a><span class="co">#completely independet regression lines</span></span>
<span id="cb95-4"><a href="RIO.html#cb95-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;a&quot;</span>,]),<span class="at">col=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb95-5"><a href="RIO.html#cb95-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;b&quot;</span>,]),<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb95-6"><a href="RIO.html#cb95-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;c&quot;</span>,]),<span class="at">col=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb95-7"><a href="RIO.html#cb95-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>data4lines[data4lines<span class="sc">$</span>z<span class="sc">==</span><span class="st">&quot;d&quot;</span>,]),<span class="at">col=</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb95-8"><a href="RIO.html#cb95-8" tabindex="-1"></a><span class="co">#these are the wrong lines... why?</span></span>
<span id="cb95-9"><a href="RIO.html#cb95-9" tabindex="-1"></a><span class="fu">abline</span>(lmlinesG,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb95-10"><a href="RIO.html#cb95-10" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb95-11"><a href="RIO.html#cb95-11" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">3</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb95-12"><a href="RIO.html#cb95-12" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">4</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb95-13"><a href="RIO.html#cb95-13" tabindex="-1"></a><span class="fu">abline</span>(lmlines<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>lmlines<span class="sc">$</span>coefficients[<span class="dv">5</span>],lmlines<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">col=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="ECOMODbook_files/figure-html/a7.16-1.png" width="672" /></p>
<p>But what is the best model to describe the data? That is a mystery that will remain to unfold. For that we will need and additional complication in a regression model: interactions.</p>
<p>But note one thing to begin with. The pooled model uses just 2 parameters, one slope and one intercept. The independent lines use 8 parameters, 4 slopes and 4 intercepts, one line for each museum. And the single model with <code>length</code> and <code>museum</code> uses 5 parameters, the intercept, the slope for <code>length</code>, and 3 parameters associated with the <span class="math inline">\(k-1=3\)</span> levels of <code>museum</code> (remember, one level of each factor is absorbed by the regression intercept).</p>
<p>So the choice of what is best might be not straightforward. While we created the data by hand, we do not know the true model! Choosing the best model requires choosing between models with different complexity, i.e. different number of parameters. We will need a parsimonious model, one that describes the data well, but with a number of parameters that is not too high for the available data. That will also require selection criteria.</p>
<p>Stay tuned for the next episodes on our regression saga!</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="handson.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ttestANOVAasLMs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ECOMODbook.pdf", "ECOMODbook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
